import type React from "react";
import { createContext, useContext, useState } from "react";

export type Language =
  | "EN"
  | "HI"
  | "TA"
  | "TE"
  | "BN"
  | "MR"
  | "GU"
  | "PA"
  | "KN"
  | "ML"
  | "OR"
  | "AS"
  | "UR"
  | "SA"
  | "KOK"
  | "MAI"
  | "SD"
  | "KS"
  | "DOI"
  | "MNI"
  | "BRX"
  | "SAT";

export interface LanguageOption {
  code: Language;
  name: string;
  nativeName: string;
}

export const LANGUAGE_OPTIONS: LanguageOption[] = [
  { code: "EN", name: "English", nativeName: "English" },
  { code: "HI", name: "Hindi", nativeName: "हिन्दी" },
  { code: "TA", name: "Tamil", nativeName: "தமிழ்" },
  { code: "TE", name: "Telugu", nativeName: "తెలుగు" },
  { code: "BN", name: "Bengali", nativeName: "বাংলা" },
  { code: "MR", name: "Marathi", nativeName: "मराठी" },
  { code: "GU", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "PA", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { code: "KN", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "ML", name: "Malayalam", nativeName: "മലയാളം" },
  { code: "OR", name: "Odia", nativeName: "ଓଡ଼ିଆ" },
  { code: "AS", name: "Assamese", nativeName: "অসমীয়া" },
  { code: "UR", name: "Urdu", nativeName: "اردو" },
  { code: "SA", name: "Sanskrit", nativeName: "संस्कृतम्" },
  { code: "KOK", name: "Konkani", nativeName: "कोंकणी" },
  { code: "MAI", name: "Maithili", nativeName: "मैथिली" },
  { code: "SD", name: "Sindhi", nativeName: "سنڌي" },
  { code: "KS", name: "Kashmiri", nativeName: "کٲشُر" },
  { code: "DOI", name: "Dogri", nativeName: "डोगरी" },
  { code: "MNI", name: "Manipuri", nativeName: "মৈতৈলোন্" },
  { code: "BRX", name: "Bodo", nativeName: "बड़ो" },
  { code: "SAT", name: "Santali", nativeName: "ᱥᱟᱱᱛᱟᱲᱤ" },
];

interface Translations {
  // Navigation
  home: string;
  loads: string;
  trips: string;
  drivers: string;
  more: string;
  // Dashboard
  dashboard: string;
  myTrucks: string;
  activeTrips: string;
  totalDrivers: string;
  monthlyEarnings: string;
  addTruck: string;
  postLoad: string;
  addDriver: string;
  hireHelper: string;
  availableLoads: string;
  earnings: string;
  postedLoads: string;
  // Load
  findLoads: string;
  filterLoads: string;
  searchLoads: string;
  pickup: string;
  delivery: string;
  distance: string;
  weight: string;
  price: string;
  truckType: string;
  // Common
  wallet: string;
  notifications: string;
  dieselCalculator: string;
  fastag: string;
  hiring: string;
  subscriptions: string;
  admin: string;
  logout: string;
  login: string;
  register: string;
  profile: string;
  settings: string;
  save: string;
  cancel: string;
  submit: string;
  close: string;
  edit: string;
  delete: string;
  approve: string;
  block: string;
  apply: string;
  calculate: string;
  recharge: string;
  withdraw: string;
  addMoney: string;
  markAllRead: string;
  // Status
  pending: string;
  accepted: string;
  loading: string;
  inTransit: string;
  delivered: string;
  cancelled: string;
  // Roles
  driver: string;
  truckOwner: string;
  transporter: string;
  helper: string;
  // Features
  gpsTracking: string;
  returnLoad: string;
  paymentSystem: string;
  // Trip
  tripManagement: string;
  // Jobs
  jobs: string;
  postJob: string;
}

const translations: Record<Language, Translations> = {
  EN: {
    home: "Home",
    loads: "Loads",
    trips: "Trips",
    drivers: "Drivers",
    more: "More",
    dashboard: "Dashboard",
    myTrucks: "My Trucks",
    activeTrips: "Active Trips",
    totalDrivers: "Total Drivers",
    monthlyEarnings: "Monthly Earnings",
    addTruck: "Add Truck",
    postLoad: "Post Load",
    addDriver: "Add Driver",
    hireHelper: "Hire Helper",
    availableLoads: "Available Loads",
    earnings: "Earnings",
    postedLoads: "Posted Loads",
    findLoads: "Find Loads",
    filterLoads: "Filter Loads",
    searchLoads: "Search Loads",
    pickup: "Pickup",
    delivery: "Delivery",
    distance: "Distance",
    weight: "Weight",
    price: "Price",
    truckType: "Truck Type",
    wallet: "Wallet",
    notifications: "Notifications",
    dieselCalculator: "Diesel Calculator",
    fastag: "FASTag",
    hiring: "Hiring",
    subscriptions: "Subscriptions",
    admin: "Admin",
    logout: "Logout",
    login: "Login",
    register: "Register",
    profile: "Profile",
    settings: "Settings",
    save: "Save",
    cancel: "Cancel",
    submit: "Submit",
    close: "Close",
    edit: "Edit",
    delete: "Delete",
    approve: "Approve",
    block: "Block",
    apply: "Apply",
    calculate: "Calculate",
    recharge: "Recharge",
    withdraw: "Withdraw",
    addMoney: "Add Money",
    markAllRead: "Mark All Read",
    pending: "Pending",
    accepted: "Accepted",
    loading: "Loading",
    inTransit: "In Transit",
    delivered: "Delivered",
    cancelled: "Cancelled",
    driver: "Driver",
    truckOwner: "Truck Owner",
    transporter: "Transporter",
    helper: "Helper",
    gpsTracking: "GPS Tracking",
    returnLoad: "Return Load",
    paymentSystem: "Payment System",
    tripManagement: "Trip Management",
    jobs: "Jobs",
    postJob: "Post Job",
  },
  HI: {
    home: "होम",
    loads: "माल",
    trips: "यात्राएं",
    drivers: "ड्राइवर",
    more: "अधिक",
    dashboard: "डैशबोर्ड",
    myTrucks: "मेरे ट्रक",
    activeTrips: "सक्रिय यात्राएं",
    totalDrivers: "कुल ड्राइवर",
    monthlyEarnings: "मासिक कमाई",
    addTruck: "ट्रक जोड़ें",
    postLoad: "माल पोस्ट करें",
    addDriver: "ड्राइवर जोड़ें",
    hireHelper: "हेल्पर रखें",
    availableLoads: "उपलब्ध माल",
    earnings: "कमाई",
    postedLoads: "पोस्ट किए माल",
    findLoads: "माल खोजें",
    filterLoads: "माल फ़िल्टर करें",
    searchLoads: "माल खोजें",
    pickup: "पिकअप",
    delivery: "डिलीवरी",
    distance: "दूरी",
    weight: "वजन",
    price: "कीमत",
    truckType: "ट्रक प्रकार",
    wallet: "बटुआ",
    notifications: "सूचनाएं",
    dieselCalculator: "डीजल कैलकुलेटर",
    fastag: "फास्टैग",
    hiring: "भर्ती",
    subscriptions: "सदस्यता",
    admin: "एडमिन",
    logout: "लॉगआउट",
    login: "लॉगिन",
    register: "रजिस्टर",
    profile: "प्रोफ़ाइल",
    settings: "सेटिंग",
    save: "सहेजें",
    cancel: "रद्द करें",
    submit: "जमा करें",
    close: "बंद करें",
    edit: "संपादित करें",
    delete: "हटाएं",
    approve: "मंज़ूर करें",
    block: "ब्लॉक करें",
    apply: "आवेदन करें",
    calculate: "गणना करें",
    recharge: "रिचार्ज",
    withdraw: "निकालें",
    addMoney: "पैसे जोड़ें",
    markAllRead: "सभी पढ़े",
    pending: "लंबित",
    accepted: "स्वीकृत",
    loading: "लोडिंग",
    inTransit: "रास्ते में",
    delivered: "डिलीवर",
    cancelled: "रद्द",
    driver: "ड्राइवर",
    truckOwner: "ट्रक मालिक",
    transporter: "ट्रांसपोर्टर",
    helper: "हेल्पर",
    gpsTracking: "GPS ट्रैकिंग",
    returnLoad: "वापसी माल",
    paymentSystem: "भुगतान प्रणाली",
    tripManagement: "यात्रा प्रबंधन",
    jobs: "नौकरियां",
    postJob: "नौकरी पोस्ट करें",
  },
  TA: {
    home: "முகப்பு",
    loads: "சரக்கு",
    trips: "பயணங்கள்",
    drivers: "ஓட்டுநர்கள்",
    more: "மேலும்",
    dashboard: "டாஷ்போர்டு",
    myTrucks: "என் லாரிகள்",
    activeTrips: "செயல் பயணங்கள்",
    totalDrivers: "மொத்த ஓட்டுநர்கள்",
    monthlyEarnings: "மாத வருமானம்",
    addTruck: "லாரி சேர்க்க",
    postLoad: "சரக்கு பதிவு",
    addDriver: "ஓட்டுநர் சேர்க்க",
    hireHelper: "உதவியாளர் அமர்த்த",
    availableLoads: "கிடைக்கும் சரக்கு",
    earnings: "வருமானம்",
    postedLoads: "பதிவிட்ட சரக்கு",
    findLoads: "சரக்கு தேட",
    filterLoads: "சரக்கு வடிகட்ட",
    searchLoads: "சரக்கு தேடல்",
    pickup: "எடுப்பு இடம்",
    delivery: "விநியோகம்",
    distance: "தூரம்",
    weight: "எடை",
    price: "விலை",
    truckType: "லாரி வகை",
    wallet: "பணப்பை",
    notifications: "அறிவிப்புகள்",
    dieselCalculator: "டீசல் கணக்கீடு",
    fastag: "ஃபாஸ்டாக்",
    hiring: "பணியமர்த்தல்",
    subscriptions: "சந்தா",
    admin: "நிர்வாகி",
    logout: "வெளியேறு",
    login: "உள்நுழை",
    register: "பதிவு",
    profile: "சுயவிவரம்",
    settings: "அமைப்புகள்",
    save: "சேமி",
    cancel: "ரத்து",
    submit: "சமர்ப்பி",
    close: "மூடு",
    edit: "திருத்து",
    delete: "நீக்கு",
    approve: "அங்கீகரி",
    block: "தடு",
    apply: "விண்ணப்பி",
    calculate: "கணக்கிடு",
    recharge: "ரீசார்ஜ்",
    withdraw: "திரும்பப்பெறு",
    addMoney: "பணம் சேர்",
    markAllRead: "அனைத்தும் படித்தது",
    pending: "நிலுவை",
    accepted: "ஏற்றுக்கொள்ளப்பட்டது",
    loading: "ஏற்றுகிறது",
    inTransit: "வழியில்",
    delivered: "விநியோகிக்கப்பட்டது",
    cancelled: "ரத்து",
    driver: "ஓட்டுநர்",
    truckOwner: "லாரி உரிமையாளர்",
    transporter: "போக்குவரத்துதாரர்",
    helper: "உதவியாளர்",
    gpsTracking: "GPS கண்காணிப்பு",
    returnLoad: "திரும்பும் சரக்கு",
    paymentSystem: "பணம் செலுத்தல்",
    tripManagement: "பயண மேலாண்மை",
    jobs: "வேலைகள்",
    postJob: "வேலை பதிவு",
  },
  TE: {
    home: "హోమ్",
    loads: "లోడ్స్",
    trips: "ట్రిప్స్",
    drivers: "డ్రైవర్లు",
    more: "మరిన్ని",
    dashboard: "డ్యాష్‌బోర్డ్",
    myTrucks: "నా ట్రక్కులు",
    activeTrips: "యాక్టివ్ ట్రిప్స్",
    totalDrivers: "మొత్తం డ్రైవర్లు",
    monthlyEarnings: "మాసిక ఆదాయం",
    addTruck: "ట్రక్ జోడించు",
    postLoad: "లోడ్ పోస్ట్",
    addDriver: "డ్రైవర్ జోడించు",
    hireHelper: "హెల్పర్ నియమించు",
    availableLoads: "అందుబాటులో లోడ్స్",
    earnings: "ఆదాయం",
    postedLoads: "పోస్ట్ చేసిన లోడ్స్",
    findLoads: "లోడ్ వెతుకు",
    filterLoads: "లోడ్ ఫిల్టర్",
    searchLoads: "లోడ్ శోధన",
    pickup: "పికప్",
    delivery: "డెలివరీ",
    distance: "దూరం",
    weight: "బరువు",
    price: "ధర",
    truckType: "ట్రక్ రకం",
    wallet: "వాలెట్",
    notifications: "నోటిఫికేషన్లు",
    dieselCalculator: "డీజిల్ కాల్క్యులేటర్",
    fastag: "ఫాస్ట్‌ట్యాగ్",
    hiring: "నియామకం",
    subscriptions: "సబ్స్క్రిప్షన్లు",
    admin: "అడ్మిన్",
    logout: "లాగౌట్",
    login: "లాగిన్",
    register: "రిజిస్టర్",
    profile: "ప్రొఫైల్",
    settings: "సెట్టింగ్స్",
    save: "సేవ్",
    cancel: "రద్దు",
    submit: "సమర్పించు",
    close: "మూసివేయి",
    edit: "సవరించు",
    delete: "తొలగించు",
    approve: "ఆమోదించు",
    block: "బ్లాక్",
    apply: "దరఖాస్తు",
    calculate: "లెక్కించు",
    recharge: "రీచార్జ్",
    withdraw: "వెనక్కి తీసుకో",
    addMoney: "డబ్బు జోడించు",
    markAllRead: "అన్నీ చదివాను",
    pending: "పెండింగ్",
    accepted: "అంగీకరించబడింది",
    loading: "లోడ్ అవుతోంది",
    inTransit: "రవాణాలో",
    delivered: "డెలివర్ చేయబడింది",
    cancelled: "రద్దు చేయబడింది",
    driver: "డ్రైవర్",
    truckOwner: "ట్రక్ యజమాని",
    transporter: "ట్రాన్స్‌పోర్టర్",
    helper: "హెల్పర్",
    gpsTracking: "GPS ట్రాకింగ్",
    returnLoad: "రిటర్న్ లోడ్",
    paymentSystem: "చెల్లింపు వ్యవస్థ",
    tripManagement: "ట్రిప్ నిర్వహణ",
    jobs: "ఉద్యోగాలు",
    postJob: "ఉద్యోగం పోస్ట్",
  },
  BN: {
    home: "হোম",
    loads: "মাল",
    trips: "ট্রিপ",
    drivers: "চালক",
    more: "আরো",
    dashboard: "ড্যাশবোর্ড",
    myTrucks: "আমার ট্রাক",
    activeTrips: "সক্রিয় ট্রিপ",
    totalDrivers: "মোট চালক",
    monthlyEarnings: "মাসিক আয়",
    addTruck: "ট্রাক যোগ করুন",
    postLoad: "মাল পোস্ট করুন",
    addDriver: "চালক যোগ করুন",
    hireHelper: "সাহায্যকারী নিয়োগ",
    availableLoads: "উপলব্ধ মাল",
    earnings: "আয়",
    postedLoads: "পোস্ট করা মাল",
    findLoads: "মাল খুঁজুন",
    filterLoads: "মাল ফিল্টার",
    searchLoads: "মাল অনুসন্ধান",
    pickup: "পিকআপ",
    delivery: "ডেলিভারি",
    distance: "দূরত্ব",
    weight: "ওজন",
    price: "মূল্য",
    truckType: "ট্রাকের ধরন",
    wallet: "ওয়ালেট",
    notifications: "বিজ্ঞপ্তি",
    dieselCalculator: "ডিজেল ক্যালকুলেটর",
    fastag: "ফাস্ট্যাগ",
    hiring: "নিয়োগ",
    subscriptions: "সাবস্ক্রিপশন",
    admin: "অ্যাডমিন",
    logout: "লগআউট",
    login: "লগইন",
    register: "রেজিস্টার",
    profile: "প্রোফাইল",
    settings: "সেটিংস",
    save: "সংরক্ষণ",
    cancel: "বাতিল",
    submit: "জমা দিন",
    close: "বন্ধ করুন",
    edit: "সম্পাদনা",
    delete: "মুছুন",
    approve: "অনুমোদন",
    block: "ব্লক",
    apply: "আবেদন",
    calculate: "গণনা",
    recharge: "রিচার্জ",
    withdraw: "উত্তোলন",
    addMoney: "টাকা যোগ করুন",
    markAllRead: "সব পড়া হয়েছে",
    pending: "মুলতুবি",
    accepted: "গৃহীত",
    loading: "লোড হচ্ছে",
    inTransit: "পথে",
    delivered: "ডেলিভার হয়েছে",
    cancelled: "বাতিল",
    driver: "চালক",
    truckOwner: "ট্রাক মালিক",
    transporter: "পরিবহনকারী",
    helper: "সাহায্যকারী",
    gpsTracking: "GPS ট্র্যাকিং",
    returnLoad: "ফেরার মাল",
    paymentSystem: "পেমেন্ট সিস্টেম",
    tripManagement: "ট্রিপ ব্যবস্থাপনা",
    jobs: "চাকরি",
    postJob: "চাকরি পোস্ট",
  },
  MR: {
    home: "मुख्यपृष्ठ",
    loads: "माल",
    trips: "प्रवास",
    drivers: "चालक",
    more: "अधिक",
    dashboard: "डॅशबोर्ड",
    myTrucks: "माझे ट्रक",
    activeTrips: "सक्रिय प्रवास",
    totalDrivers: "एकूण चालक",
    monthlyEarnings: "मासिक कमाई",
    addTruck: "ट्रक जोडा",
    postLoad: "माल पोस्ट करा",
    addDriver: "चालक जोडा",
    hireHelper: "मदतनीस नेमा",
    availableLoads: "उपलब्ध माल",
    earnings: "कमाई",
    postedLoads: "पोस्ट केलेला माल",
    findLoads: "माल शोधा",
    filterLoads: "माल फिल्टर करा",
    searchLoads: "माल शोधा",
    pickup: "उचल",
    delivery: "वितरण",
    distance: "अंतर",
    weight: "वजन",
    price: "किंमत",
    truckType: "ट्रक प्रकार",
    wallet: "पाकीट",
    notifications: "सूचना",
    dieselCalculator: "डीझेल कॅल्क्युलेटर",
    fastag: "फास्टॅग",
    hiring: "भरती",
    subscriptions: "सदस्यता",
    admin: "प्रशासक",
    logout: "लॉगआउट",
    login: "लॉगिन",
    register: "नोंदणी",
    profile: "प्रोफाइल",
    settings: "सेटिंग्ज",
    save: "जतन करा",
    cancel: "रद्द करा",
    submit: "सादर करा",
    close: "बंद करा",
    edit: "संपादित करा",
    delete: "हटवा",
    approve: "मंजूर करा",
    block: "ब्लॉक करा",
    apply: "अर्ज करा",
    calculate: "गणना करा",
    recharge: "रिचार्ज",
    withdraw: "काढा",
    addMoney: "पैसे जोडा",
    markAllRead: "सर्व वाचले",
    pending: "प्रलंबित",
    accepted: "स्वीकृत",
    loading: "लोड होत आहे",
    inTransit: "प्रवासात",
    delivered: "वितरित",
    cancelled: "रद्द",
    driver: "चालक",
    truckOwner: "ट्रक मालक",
    transporter: "वाहतूकदार",
    helper: "मदतनीस",
    gpsTracking: "GPS ट्रॅकिंग",
    returnLoad: "परतीचा माल",
    paymentSystem: "पेमेंट प्रणाली",
    tripManagement: "प्रवास व्यवस्थापन",
    jobs: "नोकऱ्या",
    postJob: "नोकरी पोस्ट करा",
  },
  GU: {
    home: "હોમ",
    loads: "માલ",
    trips: "સફર",
    drivers: "ડ્રાઇવર",
    more: "વધુ",
    dashboard: "ડૅશબોર્ડ",
    myTrucks: "મારા ટ્રક",
    activeTrips: "સક્રિય સફર",
    totalDrivers: "કુલ ડ્રાઇવર",
    monthlyEarnings: "માસિક કમાણી",
    addTruck: "ટ્રક ઉમેરો",
    postLoad: "માલ પોસ્ટ કરો",
    addDriver: "ડ્રાઇવર ઉમેરો",
    hireHelper: "મદદનીશ રાખો",
    availableLoads: "ઉપલબ્ધ માલ",
    earnings: "કમાણી",
    postedLoads: "પોસ્ટ કરેલ માલ",
    findLoads: "માલ શોધો",
    filterLoads: "માલ ફિલ્ટર",
    searchLoads: "માલ શોધ",
    pickup: "પિકઅપ",
    delivery: "ડિલિવરી",
    distance: "અંતર",
    weight: "વજન",
    price: "ભાવ",
    truckType: "ટ્રક પ્રકાર",
    wallet: "વૉલેટ",
    notifications: "સૂચનાઓ",
    dieselCalculator: "ડીઝેલ કૅલ્ક્યુલેટર",
    fastag: "ફાસ્ટૅગ",
    hiring: "ભરતી",
    subscriptions: "સભ્યપદ",
    admin: "એડ્મિન",
    logout: "લૉગઆઉટ",
    login: "લૉગિન",
    register: "નોંધણી",
    profile: "પ્રોફાઇલ",
    settings: "સેટિંગ્સ",
    save: "સાચવો",
    cancel: "રદ કરો",
    submit: "સબમિટ",
    close: "બંધ",
    edit: "સંપાદિત",
    delete: "કાઢો",
    approve: "મંજૂર",
    block: "બ્લૉક",
    apply: "અરજી",
    calculate: "ગણો",
    recharge: "રિચાર્જ",
    withdraw: "ઉપાડ",
    addMoney: "પૈસા ઉમેરો",
    markAllRead: "બધું વાંચ્યું",
    pending: "બાકી",
    accepted: "સ્વીકૃત",
    loading: "લોડ થઈ રહ્યું",
    inTransit: "રસ્તામાં",
    delivered: "ડિલિવર",
    cancelled: "રદ",
    driver: "ડ્રાઇવર",
    truckOwner: "ટ્રક માલિક",
    transporter: "ટ્રાન્સપોર્ટર",
    helper: "મદદનીશ",
    gpsTracking: "GPS ટ્રૅકિંગ",
    returnLoad: "પરત માલ",
    paymentSystem: "ચુકવણી પ્રણાલી",
    tripManagement: "સફર વ્યવસ્થાપન",
    jobs: "નોકરી",
    postJob: "નોકરી પોસ્ટ",
  },
  PA: {
    home: "ਹੋਮ",
    loads: "ਮਾਲ",
    trips: "ਯਾਤਰਾਵਾਂ",
    drivers: "ਡਰਾਈਵਰ",
    more: "ਹੋਰ",
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    myTrucks: "ਮੇਰੇ ਟਰੱਕ",
    activeTrips: "ਕਿਰਿਆਸ਼ੀਲ ਯਾਤਰਾਵਾਂ",
    totalDrivers: "ਕੁੱਲ ਡਰਾਈਵਰ",
    monthlyEarnings: "ਮਾਸਿਕ ਕਮਾਈ",
    addTruck: "ਟਰੱਕ ਜੋੜੋ",
    postLoad: "ਮਾਲ ਪੋਸਟ ਕਰੋ",
    addDriver: "ਡਰਾਈਵਰ ਜੋੜੋ",
    hireHelper: "ਮਦਦਗਾਰ ਰੱਖੋ",
    availableLoads: "ਉਪਲਬਧ ਮਾਲ",
    earnings: "ਕਮਾਈ",
    postedLoads: "ਪੋਸਟ ਕੀਤਾ ਮਾਲ",
    findLoads: "ਮਾਲ ਲੱਭੋ",
    filterLoads: "ਮਾਲ ਫਿਲਟਰ",
    searchLoads: "ਮਾਲ ਖੋਜ",
    pickup: "ਪਿਕਅੱਪ",
    delivery: "ਡਿਲਿਵਰੀ",
    distance: "ਦੂਰੀ",
    weight: "ਭਾਰ",
    price: "ਕੀਮਤ",
    truckType: "ਟਰੱਕ ਕਿਸਮ",
    wallet: "ਬਟੂਆ",
    notifications: "ਸੂਚਨਾਵਾਂ",
    dieselCalculator: "ਡੀਜ਼ਲ ਕੈਲਕੁਲੇਟਰ",
    fastag: "ਫਾਸਟੈਗ",
    hiring: "ਭਰਤੀ",
    subscriptions: "ਸਬਸਕ੍ਰਿਪਸ਼ਨ",
    admin: "ਪ੍ਰਬੰਧਕ",
    logout: "ਲਾਗਆਊਟ",
    login: "ਲਾਗਇਨ",
    register: "ਰਜਿਸਟਰ",
    profile: "ਪ੍ਰੋਫਾਈਲ",
    settings: "ਸੈਟਿੰਗਜ਼",
    save: "ਸੁਰੱਖਿਅਤ",
    cancel: "ਰੱਦ",
    submit: "ਜਮ੍ਹਾਂ",
    close: "ਬੰਦ",
    edit: "ਸੋਧੋ",
    delete: "ਮਿਟਾਓ",
    approve: "ਮਨਜ਼ੂਰ",
    block: "ਬਲਾਕ",
    apply: "ਅਰਜ਼ੀ",
    calculate: "ਗਣਨਾ",
    recharge: "ਰੀਚਾਰਜ",
    withdraw: "ਕਢਵਾਓ",
    addMoney: "ਪੈਸੇ ਜੋੜੋ",
    markAllRead: "ਸਭ ਪੜ੍ਹਿਆ",
    pending: "ਲੰਬਿਤ",
    accepted: "ਸਵੀਕਾਰ",
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ",
    inTransit: "ਰਸਤੇ ਵਿੱਚ",
    delivered: "ਡਿਲਿਵਰ",
    cancelled: "ਰੱਦ",
    driver: "ਡਰਾਈਵਰ",
    truckOwner: "ਟਰੱਕ ਮਾਲਕ",
    transporter: "ਟਰਾਂਸਪੋਰਟਰ",
    helper: "ਮਦਦਗਾਰ",
    gpsTracking: "GPS ਟ੍ਰੈਕਿੰਗ",
    returnLoad: "ਵਾਪਸੀ ਮਾਲ",
    paymentSystem: "ਭੁਗਤਾਨ ਪ੍ਰਣਾਲੀ",
    tripManagement: "ਯਾਤਰਾ ਪ੍ਰਬੰਧਨ",
    jobs: "ਨੌਕਰੀਆਂ",
    postJob: "ਨੌਕਰੀ ਪੋਸਟ",
  },
  KN: {
    home: "ಮನೆ",
    loads: "ಸರಕು",
    trips: "ಪ್ರಯಾಣಗಳು",
    drivers: "ಚಾಲಕರು",
    more: "ಹೆಚ್ಚು",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    myTrucks: "ನನ್ನ ಟ್ರಕ್ಕುಗಳು",
    activeTrips: "ಸಕ್ರಿಯ ಪ್ರಯಾಣಗಳು",
    totalDrivers: "ಒಟ್ಟು ಚಾಲಕರು",
    monthlyEarnings: "ಮಾಸಿಕ ಆದಾಯ",
    addTruck: "ಟ್ರಕ್ ಸೇರಿಸಿ",
    postLoad: "ಸರಕು ಪೋಸ್ಟ್",
    addDriver: "ಚಾಲಕ ಸೇರಿಸಿ",
    hireHelper: "ಸಹಾಯಕ ನೇಮಿಸಿ",
    availableLoads: "ಲಭ್ಯ ಸರಕು",
    earnings: "ಆದಾಯ",
    postedLoads: "ಪೋಸ್ಟ್ ಸರಕು",
    findLoads: "ಸರಕು ಹುಡುಕಿ",
    filterLoads: "ಸರಕು ಫಿಲ್ಟರ್",
    searchLoads: "ಸರಕು ಹುಡುಕಾಟ",
    pickup: "ಪಿಕಪ್",
    delivery: "ವಿತರಣೆ",
    distance: "ದೂರ",
    weight: "ತೂಕ",
    price: "ಬೆಲೆ",
    truckType: "ಟ್ರಕ್ ವಿಧ",
    wallet: "ವ್ಯಾಲೆಟ್",
    notifications: "ಅಧಿಸೂಚನೆಗಳು",
    dieselCalculator: "ಡೀಸೆಲ್ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    fastag: "ಫಾಸ್ಟ್ಯಾಗ್",
    hiring: "ನೇಮಕಾತಿ",
    subscriptions: "ಸದಸ್ಯತೆ",
    admin: "ನಿರ್ವಾಹಕ",
    logout: "ಲಾಗ್‌ಔಟ್",
    login: "ಲಾಗಿನ್",
    register: "ನೋಂದಣಿ",
    profile: "ಪ್ರೊಫೈಲ್",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    save: "ಉಳಿಸಿ",
    cancel: "ರದ್ದು",
    submit: "ಸಲ್ಲಿಸಿ",
    close: "ಮುಚ್ಚಿ",
    edit: "ಸಂಪಾದಿಸಿ",
    delete: "ಅಳಿಸಿ",
    approve: "ಅನುಮೋದಿಸಿ",
    block: "ತಡೆ",
    apply: "ಅರ್ಜಿ",
    calculate: "ಲೆಕ್ಕ ಹಾಕಿ",
    recharge: "ರೀಚಾರ್ಜ್",
    withdraw: "ಹಿಂಪಡೆಯಿರಿ",
    addMoney: "ಹಣ ಸೇರಿಸಿ",
    markAllRead: "ಎಲ್ಲ ಓದಿದೆ",
    pending: "ಬಾಕಿ",
    accepted: "ಸ್ವೀಕೃತ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ",
    inTransit: "ಸಾಗಣೆಯಲ್ಲಿ",
    delivered: "ವಿತರಿಸಲಾಗಿದೆ",
    cancelled: "ರದ್ದು",
    driver: "ಚಾಲಕ",
    truckOwner: "ಟ್ರಕ್ ಮಾಲೀಕ",
    transporter: "ಸಾರಿಗೆದಾರ",
    helper: "ಸಹಾಯಕ",
    gpsTracking: "GPS ಟ್ರ್ಯಾಕಿಂಗ್",
    returnLoad: "ಹಿಂತಿರುಗುವ ಸರಕು",
    paymentSystem: "ಪಾವತಿ ವ್ಯವಸ್ಥೆ",
    tripManagement: "ಪ್ರಯಾಣ ನಿರ್ವಹಣೆ",
    jobs: "ಉದ್ಯೋಗಗಳು",
    postJob: "ಉದ್ಯೋಗ ಪೋಸ್ಟ್",
  },
  ML: {
    home: "ഹോം",
    loads: "ചരക്ക്",
    trips: "യാത്രകൾ",
    drivers: "ഡ്രൈവർമാർ",
    more: "കൂടുതൽ",
    dashboard: "ഡാഷ്‌ബോർഡ്",
    myTrucks: "എന്റെ ട്രക്കുകൾ",
    activeTrips: "സജീവ യാത്രകൾ",
    totalDrivers: "ആകെ ഡ്രൈവർമാർ",
    monthlyEarnings: "മാസ വരുമാനം",
    addTruck: "ട്രക്ക് ചേർക്കുക",
    postLoad: "ചരക്ക് പോസ്റ്റ്",
    addDriver: "ഡ്രൈവർ ചേർക്കുക",
    hireHelper: "സഹായി നിയമിക്കുക",
    availableLoads: "ലഭ്യമായ ചരക്ക്",
    earnings: "വരുമാനം",
    postedLoads: "പോസ്റ്റ് ചരക്ക്",
    findLoads: "ചരക്ക് കണ്ടെത്തുക",
    filterLoads: "ചരക്ക് ഫിൽറ്റർ",
    searchLoads: "ചരക്ക് തിരയൽ",
    pickup: "പിക്കപ്പ്",
    delivery: "ഡെലിവറി",
    distance: "ദൂരം",
    weight: "ഭാരം",
    price: "വില",
    truckType: "ട്രക്ക് തരം",
    wallet: "വാലറ്റ്",
    notifications: "അറിയിപ്പുകൾ",
    dieselCalculator: "ഡീസൽ കാൽക്കുലേറ്റർ",
    fastag: "ഫാസ്റ്റാഗ്",
    hiring: "നിയമനം",
    subscriptions: "സബ്സ്ക്രിപ്ഷൻ",
    admin: "അഡ്മിൻ",
    logout: "ലോഗൗട്ട്",
    login: "ലോഗിൻ",
    register: "രജിസ്റ്റർ",
    profile: "പ്രൊഫൈൽ",
    settings: "ക്രമീകരണങ്ങൾ",
    save: "സേവ് ചെയ്യുക",
    cancel: "റദ്ദാക്കുക",
    submit: "സമർപ്പിക്കുക",
    close: "അടയ്ക്കുക",
    edit: "എഡിറ്റ്",
    delete: "ഇല്ലാതാക്കുക",
    approve: "അംഗീകരിക്കുക",
    block: "ബ്ലോക്ക്",
    apply: "അപേക്ഷ",
    calculate: "കണക്കാക്കുക",
    recharge: "റീചാർജ്",
    withdraw: "പിൻവലിക്കുക",
    addMoney: "പണം ചേർക്കുക",
    markAllRead: "എല്ലാം വായിച്ചു",
    pending: "തീർപ്പുകൽപ്പിക്കാത്ത",
    accepted: "സ്വീകരിച്ചു",
    loading: "ലോഡ് ആകുന്നു",
    inTransit: "ട്രാൻസിറ്റിൽ",
    delivered: "ഡെലിവർ ചെയ്തു",
    cancelled: "റദ്ദ്",
    driver: "ഡ്രൈവർ",
    truckOwner: "ട്രക്ക് ഉടമ",
    transporter: "ഗതാഗതക്കാരൻ",
    helper: "സഹായി",
    gpsTracking: "GPS ട്രാക്കിംഗ്",
    returnLoad: "മടക്ക ചരക്ക്",
    paymentSystem: "പേയ്‌മെന്റ് സിസ്റ്റം",
    tripManagement: "യാത്രാ മാനേജ്‌മെന്റ്",
    jobs: "ജോലികൾ",
    postJob: "ജോലി പോസ്റ്റ്",
  },
  OR: {
    home: "ହୋମ",
    loads: "ଭାର",
    trips: "ଯାତ୍ରା",
    drivers: "ଚାଳକ",
    more: "ଅଧିକ",
    dashboard: "ଡ୍ୟାସ୍ବୋର୍ଡ",
    myTrucks: "ମୋ ଟ୍ରକ୍",
    activeTrips: "ସକ୍ରିୟ ଯାତ୍ରା",
    totalDrivers: "ମୋଟ ଚାଳକ",
    monthlyEarnings: "ମାସିକ ଆୟ",
    addTruck: "ଟ୍ରକ ଯୋଡ଼ନ୍ତୁ",
    postLoad: "ଭାର ପୋଷ୍ଟ",
    addDriver: "ଚାଳକ ଯୋଡ଼ନ୍ତୁ",
    hireHelper: "ସହାୟକ ରଖନ୍ତୁ",
    availableLoads: "ଉପଲବ୍ଧ ଭାର",
    earnings: "ଆୟ",
    postedLoads: "ପୋଷ୍ଟ ଭାର",
    findLoads: "ଭାର ଖୋଜନ୍ତୁ",
    filterLoads: "ଭାର ଫିଲ୍ଟର",
    searchLoads: "ଭାର ଖୋଜ",
    pickup: "ପିକଅପ",
    delivery: "ଡେଲିଭରି",
    distance: "ଦୂରତ୍ୱ",
    weight: "ଓଜନ",
    price: "ମୂଲ୍ୟ",
    truckType: "ଟ୍ରକ ପ୍ରକାର",
    wallet: "ୱାଲେଟ",
    notifications: "ବିଜ୍ଞପ୍ତି",
    dieselCalculator: "ଡିଜେଲ କ୍ୟାଲ୍କୁଲେଟର",
    fastag: "ଫାଷ୍ଟ୍ୟାଗ",
    hiring: "ନିଯୁକ୍ତି",
    subscriptions: "ସଦସ୍ୟତା",
    admin: "ଆଡ୍ମିନ",
    logout: "ଲଗଆଉଟ",
    login: "ଲଗଇନ",
    register: "ପଞ୍ଜୀକରଣ",
    profile: "ପ୍ରୋଫାଇଲ",
    settings: "ସେଟିଂ",
    save: "ସଞ୍ଚୟ",
    cancel: "ବାତିଲ",
    submit: "ଜମା",
    close: "ବନ୍ଦ",
    edit: "ସଂପାଦନ",
    delete: "ଡିଲିଟ",
    approve: "ଅନୁମୋଦନ",
    block: "ବ୍ଲକ",
    apply: "ଆବେଦନ",
    calculate: "ଗଣନା",
    recharge: "ରିଚାର୍ଜ",
    withdraw: "ଉଠାନ",
    addMoney: "ଟଙ୍କା ଯୋଡ଼ନ୍ତୁ",
    markAllRead: "ସବୁ ପଢ଼ାଗଲା",
    pending: "ଅପେକ୍ଷାରତ",
    accepted: "ଗ୍ରହଣ",
    loading: "ଲୋଡ଼ ହେଉଛି",
    inTransit: "ରାସ୍ତାରେ",
    delivered: "ଡେଲିଭର",
    cancelled: "ବାତିଲ",
    driver: "ଚାଳକ",
    truckOwner: "ଟ୍ରକ ମାଲିକ",
    transporter: "ପରିବହନକାରୀ",
    helper: "ସହାୟକ",
    gpsTracking: "GPS ଟ୍ରାକିଂ",
    returnLoad: "ଫେରତ ଭାର",
    paymentSystem: "ଦେୟ ପ୍ରଣାଳୀ",
    tripManagement: "ଯାତ୍ରା ପ୍ରବନ୍ଧ",
    jobs: "ଚାକିରି",
    postJob: "ଚାକିରି ପୋଷ୍ଟ",
  },
  AS: {
    home: "হোম",
    loads: "মাল",
    trips: "যাত্ৰা",
    drivers: "চালক",
    more: "অধিক",
    dashboard: "ডেশ্বোৰ্ড",
    myTrucks: "মোৰ ট্ৰাক",
    activeTrips: "সক্ৰিয় যাত্ৰা",
    totalDrivers: "মুঠ চালক",
    monthlyEarnings: "মাহেকীয়া উপাৰ্জন",
    addTruck: "ট্ৰাক যোগ",
    postLoad: "মাল পোষ্ট",
    addDriver: "চালক যোগ",
    hireHelper: "সহায়ক ৰাখক",
    availableLoads: "উপলব্ধ মাল",
    earnings: "উপাৰ্জন",
    postedLoads: "পোষ্ট মাল",
    findLoads: "মাল বিচাৰক",
    filterLoads: "মাল ফিল্টাৰ",
    searchLoads: "মাল সন্ধান",
    pickup: "পিকআপ",
    delivery: "ডেলিভাৰী",
    distance: "দূৰত্ব",
    weight: "ওজন",
    price: "মূল্য",
    truckType: "ট্ৰাকৰ ধৰন",
    wallet: "ৱালেট",
    notifications: "জাননী",
    dieselCalculator: "ডিজেল কেলকুলেটৰ",
    fastag: "ফাষ্টেগ",
    hiring: "নিয়োগ",
    subscriptions: "চাবস্ক্রিপ্চন",
    admin: "এডমিন",
    logout: "লগআউট",
    login: "লগইন",
    register: "পঞ্জীয়ন",
    profile: "প্ৰ'ফাইল",
    settings: "ছেটিং",
    save: "সঞ্চয়",
    cancel: "বাতিল",
    submit: "দাখিল",
    close: "বন্ধ",
    edit: "সম্পাদনা",
    delete: "মচক",
    approve: "অনুমোদন",
    block: "ব্লক",
    apply: "আবেদন",
    calculate: "গণনা",
    recharge: "ৰিচাৰ্জ",
    withdraw: "উলিওৱা",
    addMoney: "টকা যোগ",
    markAllRead: "সকলো পঢ়া হ'ল",
    pending: "বিচাৰাধীন",
    accepted: "গৃহীত",
    loading: "লোড হৈছে",
    inTransit: "পথত",
    delivered: "ডেলিভাৰী",
    cancelled: "বাতিল",
    driver: "চালক",
    truckOwner: "ট্ৰাক মালিক",
    transporter: "পৰিবাহনকাৰী",
    helper: "সহায়ক",
    gpsTracking: "GPS ট্ৰেকিং",
    returnLoad: "ঘূৰতি মাল",
    paymentSystem: "পেমেন্ট ব্যৱস্থা",
    tripManagement: "যাত্ৰা ব্যৱস্থাপনা",
    jobs: "চাকৰি",
    postJob: "চাকৰি পোষ্ট",
  },
  UR: {
    home: "ہوم",
    loads: "مال",
    trips: "سفر",
    drivers: "ڈرائیور",
    more: "مزید",
    dashboard: "ڈیش بورڈ",
    myTrucks: "میرے ٹرک",
    activeTrips: "فعال سفر",
    totalDrivers: "کل ڈرائیور",
    monthlyEarnings: "ماہانہ آمدنی",
    addTruck: "ٹرک شامل کریں",
    postLoad: "مال پوسٹ کریں",
    addDriver: "ڈرائیور شامل کریں",
    hireHelper: "مددگار رکھیں",
    availableLoads: "دستیاب مال",
    earnings: "آمدنی",
    postedLoads: "پوسٹ مال",
    findLoads: "مال تلاش کریں",
    filterLoads: "مال فلٹر",
    searchLoads: "مال تلاش",
    pickup: "پک اپ",
    delivery: "ڈیلیوری",
    distance: "فاصلہ",
    weight: "وزن",
    price: "قیمت",
    truckType: "ٹرک قسم",
    wallet: "بٹوہ",
    notifications: "اطلاعات",
    dieselCalculator: "ڈیزل کیلکولیٹر",
    fastag: "فاسٹیگ",
    hiring: "بھرتی",
    subscriptions: "سبسکرپشن",
    admin: "ایڈمن",
    logout: "لاگ آؤٹ",
    login: "لاگ ان",
    register: "رجسٹر",
    profile: "پروفائل",
    settings: "ترتیبات",
    save: "محفوظ",
    cancel: "منسوخ",
    submit: "جمع",
    close: "بند",
    edit: "ترمیم",
    delete: "حذف",
    approve: "منظور",
    block: "بلاک",
    apply: "درخواست",
    calculate: "حساب",
    recharge: "ریچارج",
    withdraw: "نکالیں",
    addMoney: "پیسے شامل",
    markAllRead: "سب پڑھا",
    pending: "زیر التوا",
    accepted: "منظور شدہ",
    loading: "لوڈ ہو رہا",
    inTransit: "راستے میں",
    delivered: "ڈیلیور",
    cancelled: "منسوخ",
    driver: "ڈرائیور",
    truckOwner: "ٹرک مالک",
    transporter: "ٹرانسپورٹر",
    helper: "مددگار",
    gpsTracking: "GPS ٹریکنگ",
    returnLoad: "واپسی مال",
    paymentSystem: "ادائیگی نظام",
    tripManagement: "سفر انتظام",
    jobs: "نوکریاں",
    postJob: "نوکری پوسٹ",
  },
  SA: {
    home: "गृहम्",
    loads: "भारः",
    trips: "यात्राः",
    drivers: "चालकाः",
    more: "अधिकम्",
    dashboard: "नियन्त्रणपटलम्",
    myTrucks: "मम वाहनानि",
    activeTrips: "सक्रियाः यात्राः",
    totalDrivers: "सर्वे चालकाः",
    monthlyEarnings: "मासिकम् अर्जनम्",
    addTruck: "वाहनम् योजयतु",
    postLoad: "भारः प्रेषयतु",
    addDriver: "चालकः योजयतु",
    hireHelper: "सहायकः नियोजयतु",
    availableLoads: "लब्धव्याः भाराः",
    earnings: "अर्जनम्",
    postedLoads: "प्रेषिताः भाराः",
    findLoads: "भारम् अन्वेषयतु",
    filterLoads: "भारम् शोधयतु",
    searchLoads: "भारम् अन्वेषणम्",
    pickup: "ग्रहणम्",
    delivery: "वितरणम्",
    distance: "दूरत्वम्",
    weight: "भारः",
    price: "मूल्यम्",
    truckType: "वाहनप्रकारः",
    wallet: "धनकोशः",
    notifications: "सूचनाः",
    dieselCalculator: "डीजल गणकम्",
    fastag: "द्रुतचिह्नम्",
    hiring: "नियोगः",
    subscriptions: "सदस्यता",
    admin: "प्रशासकः",
    logout: "निर्गमनम्",
    login: "प्रवेशः",
    register: "पञ्जीकरणम्",
    profile: "परिचयः",
    settings: "व्यवस्थाः",
    save: "रक्षतु",
    cancel: "निरस्तु",
    submit: "प्रेषयतु",
    close: "बन्धयतु",
    edit: "सम्पादयतु",
    delete: "अपाकरोतु",
    approve: "अनुमोदयतु",
    block: "अवरुद्धयतु",
    apply: "निवेदयतु",
    calculate: "गणयतु",
    recharge: "पुनःपूर्णम्",
    withdraw: "निष्कासयतु",
    addMoney: "धनम् योजयतु",
    markAllRead: "सर्वं पठितम्",
    pending: "प्रतीक्षामाणम्",
    accepted: "स्वीकृतम्",
    loading: "लोड्यते",
    inTransit: "मार्गे",
    delivered: "वितरितम्",
    cancelled: "रद्दम्",
    driver: "चालकः",
    truckOwner: "वाहनस्वामी",
    transporter: "वाहकः",
    helper: "सहायकः",
    gpsTracking: "GPS अनुगमनम्",
    returnLoad: "प्रत्यागमनभारः",
    paymentSystem: "भुगतानव्यवस्था",
    tripManagement: "यात्राप्रबन्धनम्",
    jobs: "कार्याणि",
    postJob: "कार्यम् प्रेषयतु",
  },
  KOK: {
    home: "होम",
    loads: "माल",
    trips: "प्रवास",
    drivers: "चालक",
    more: "चड्डें",
    dashboard: "डॅशबोर्ड",
    myTrucks: "माझे ट्रक",
    activeTrips: "सक्रिय प्रवास",
    totalDrivers: "एकूण चालक",
    monthlyEarnings: "मासिक उत्पन्न",
    addTruck: "ट्रक घाल",
    postLoad: "माल पोस्ट",
    addDriver: "चालक घाल",
    hireHelper: "मदतनीस नेमा",
    availableLoads: "उपलब्ध माल",
    earnings: "उत्पन्न",
    postedLoads: "पोस्ट केलो माल",
    findLoads: "माल सोध",
    filterLoads: "माल फिल्टर",
    searchLoads: "माल सोध",
    pickup: "पिकअप",
    delivery: "डिलिव्हरी",
    distance: "अंतर",
    weight: "वजन",
    price: "किंमत",
    truckType: "ट्रक प्रकार",
    wallet: "पाकीट",
    notifications: "सूचना",
    dieselCalculator: "डीझेल कॅल्क्युलेटर",
    fastag: "फास्टॅग",
    hiring: "भरती",
    subscriptions: "सदस्यता",
    admin: "प्रशासक",
    logout: "लॉगआउट",
    login: "लॉगिन",
    register: "नोंदणी",
    profile: "प्रोफाइल",
    settings: "सेटिंग",
    save: "जतन",
    cancel: "रद्द",
    submit: "सादर",
    close: "बंद",
    edit: "संपादन",
    delete: "हटव",
    approve: "मंजूर",
    block: "ब्लॉक",
    apply: "अर्ज",
    calculate: "गणना",
    recharge: "रिचार्ज",
    withdraw: "काढ",
    addMoney: "पैसे घाल",
    markAllRead: "सर्व वाचलें",
    pending: "प्रलंबित",
    accepted: "स्वीकृत",
    loading: "लोड होतां",
    inTransit: "प्रवासांत",
    delivered: "वितरित",
    cancelled: "रद्द",
    driver: "चालक",
    truckOwner: "ट्रक मालक",
    transporter: "वाहतूकदार",
    helper: "मदतनीस",
    gpsTracking: "GPS ट्रॅकिंग",
    returnLoad: "परतीचो माल",
    paymentSystem: "पेमेंट प्रणाली",
    tripManagement: "प्रवास व्यवस्थापन",
    jobs: "नोकऱ्यो",
    postJob: "नोकरी पोस्ट",
  },
  MAI: {
    home: "होम",
    loads: "माल",
    trips: "यात्रा",
    drivers: "चालक",
    more: "आरो",
    dashboard: "डैशबोर्ड",
    myTrucks: "हमर ट्रक",
    activeTrips: "सक्रिय यात्रा",
    totalDrivers: "कुल चालक",
    monthlyEarnings: "मासिक कमाई",
    addTruck: "ट्रक जोड़ू",
    postLoad: "माल पोस्ट करू",
    addDriver: "चालक जोड़ू",
    hireHelper: "सहायक रखू",
    availableLoads: "उपलब्ध माल",
    earnings: "कमाई",
    postedLoads: "पोस्ट माल",
    findLoads: "माल खोजू",
    filterLoads: "माल फिल्टर",
    searchLoads: "माल खोज",
    pickup: "पिकअप",
    delivery: "डिलीवरी",
    distance: "दूरी",
    weight: "वजन",
    price: "कीमत",
    truckType: "ट्रक प्रकार",
    wallet: "बटुआ",
    notifications: "सूचना",
    dieselCalculator: "डीजल कैलकुलेटर",
    fastag: "फास्टैग",
    hiring: "भर्ती",
    subscriptions: "सदस्यता",
    admin: "एडमिन",
    logout: "लॉगआउट",
    login: "लॉगिन",
    register: "रजिस्टर",
    profile: "प्रोफाइल",
    settings: "सेटिंग",
    save: "सेव करू",
    cancel: "रद्द करू",
    submit: "जमा करू",
    close: "बंद करू",
    edit: "संपादन",
    delete: "हटाउ",
    approve: "मंजूर",
    block: "ब्लॉक",
    apply: "आवेदन",
    calculate: "गणना",
    recharge: "रिचार्ज",
    withdraw: "निकालू",
    addMoney: "पैसा जोड़ू",
    markAllRead: "सब पढ़लहुं",
    pending: "लंबित",
    accepted: "स्वीकृत",
    loading: "लोड होइत",
    inTransit: "रास्तामे",
    delivered: "डिलीवर",
    cancelled: "रद्द",
    driver: "चालक",
    truckOwner: "ट्रक मालिक",
    transporter: "ट्रांसपोर्टर",
    helper: "सहायक",
    gpsTracking: "GPS ट्रैकिंग",
    returnLoad: "वापसी माल",
    paymentSystem: "भुगतान प्रणाली",
    tripManagement: "यात्रा प्रबंधन",
    jobs: "नौकरी",
    postJob: "नौकरी पोस्ट",
  },
  SD: {
    home: "گهر",
    loads: "مال",
    trips: "سفر",
    drivers: "ڊرائيور",
    more: "وڌيڪ",
    dashboard: "ڊيش بورڊ",
    myTrucks: "منهنجا ٽرڪ",
    activeTrips: "فعال سفر",
    totalDrivers: "ڪل ڊرائيور",
    monthlyEarnings: "مهيني آمدني",
    addTruck: "ٽرڪ شامل ڪريو",
    postLoad: "مال پوسٽ",
    addDriver: "ڊرائيور شامل",
    hireHelper: "مددگار رکو",
    availableLoads: "دستياب مال",
    earnings: "آمدني",
    postedLoads: "پوسٽ مال",
    findLoads: "مال ڳولهيو",
    filterLoads: "مال فلٽر",
    searchLoads: "مال ڳولها",
    pickup: "پڪ اپ",
    delivery: "ڊليوري",
    distance: "فاصلو",
    weight: "وزن",
    price: "قيمت",
    truckType: "ٽرڪ قسم",
    wallet: "بٽوو",
    notifications: "اطلاع",
    dieselCalculator: "ڊيزل حساب",
    fastag: "فاسٽيگ",
    hiring: "ڀرتي",
    subscriptions: "سبسڪرپشن",
    admin: "ايڊمن",
    logout: "لاگ آئوٽ",
    login: "لاگ ان",
    register: "رجسٽر",
    profile: "پروفائل",
    settings: "ترتيبون",
    save: "محفوظ",
    cancel: "رد",
    submit: "جمع",
    close: "بند",
    edit: "ترميم",
    delete: "ختم",
    approve: "منظور",
    block: "بلاڪ",
    apply: "درخواست",
    calculate: "حساب",
    recharge: "ريچارج",
    withdraw: "ڪڍو",
    addMoney: "پئسا شامل",
    markAllRead: "سڀ پڙهيو",
    pending: "زير التوا",
    accepted: "قبول",
    loading: "لوڊ ٿيندو",
    inTransit: "رستي ۾",
    delivered: "ڊليور",
    cancelled: "رد",
    driver: "ڊرائيور",
    truckOwner: "ٽرڪ مالڪ",
    transporter: "ٽرانسپورٽر",
    helper: "مددگار",
    gpsTracking: "GPS ٽريڪنگ",
    returnLoad: "واپسي مال",
    paymentSystem: "ادائيگي نظام",
    tripManagement: "سفر انتظام",
    jobs: "نوڪريون",
    postJob: "نوڪري پوسٽ",
  },
  KS: {
    home: "ہوم",
    loads: "بار",
    trips: "سفر",
    drivers: "ڈرایوَر",
    more: "زیادہ",
    dashboard: "ڈیش بورڈ",
    myTrucks: "میون ٹرٕک",
    activeTrips: "فعال سفر",
    totalDrivers: "کُل ڈرایوَر",
    monthlyEarnings: "ماہانہ کمائی",
    addTruck: "ٹرٕک وَتھاوو",
    postLoad: "بار پوسٹ",
    addDriver: "ڈرایوَر وَتھاوو",
    hireHelper: "مددگار رَکھو",
    availableLoads: "دستیاب بار",
    earnings: "کمائی",
    postedLoads: "پوسٹ بار",
    findLoads: "بار لَبھو",
    filterLoads: "بار فلٹر",
    searchLoads: "بار تلاش",
    pickup: "پِک اَپ",
    delivery: "ڈیلیوری",
    distance: "فاصلہ",
    weight: "وزن",
    price: "قیمت",
    truckType: "ٹرٕک قِسم",
    wallet: "بَٹوہ",
    notifications: "اطلاعات",
    dieselCalculator: "ڈیزل کیلکولیٹر",
    fastag: "فاسٹیگ",
    hiring: "بھرتی",
    subscriptions: "سدسیتا",
    admin: "ایڈمِن",
    logout: "لاگ آؤٹ",
    login: "لاگِن",
    register: "رجِسٹر",
    profile: "پروفایِل",
    settings: "ترتیبات",
    save: "محفوظ",
    cancel: "رَد",
    submit: "جمع",
    close: "بند",
    edit: "ترمیم",
    delete: "حذف",
    approve: "منظور",
    block: "بلاک",
    apply: "درخواست",
    calculate: "حساب",
    recharge: "ریچارج",
    withdraw: "نِکالو",
    addMoney: "پَیسے وَتھاوو",
    markAllRead: "سب پَڑھِتھ",
    pending: "انتظار",
    accepted: "منظور",
    loading: "لوڈ ہاوان",
    inTransit: "راستہ مَنز",
    delivered: "ڈیلیور",
    cancelled: "رَد",
    driver: "ڈرایوَر",
    truckOwner: "ٹرٕک مالِک",
    transporter: "ٹرانسپورٹر",
    helper: "مددگار",
    gpsTracking: "GPS ٹریکِنگ",
    returnLoad: "واپسی بار",
    paymentSystem: "ادائیگی نِظام",
    tripManagement: "سفر انتِظام",
    jobs: "نوکریاں",
    postJob: "نوکری پوسٹ",
  },
  DOI: {
    home: "होम",
    loads: "माल",
    trips: "यात्रा",
    drivers: "ड्राइवर",
    more: "होर",
    dashboard: "डैशबोर्ड",
    myTrucks: "मेरे ट्रक",
    activeTrips: "सक्रिय यात्रा",
    totalDrivers: "कुल ड्राइवर",
    monthlyEarnings: "मासिक कमाई",
    addTruck: "ट्रक जोड़ो",
    postLoad: "माल पोस्ट करो",
    addDriver: "ड्राइवर जोड़ो",
    hireHelper: "मददगार राखो",
    availableLoads: "उपलब्ध माल",
    earnings: "कमाई",
    postedLoads: "पोस्ट माल",
    findLoads: "माल लब्बो",
    filterLoads: "माल फिल्टर",
    searchLoads: "माल लब्भाई",
    pickup: "पिकअप",
    delivery: "डिलीवरी",
    distance: "दूरी",
    weight: "भार",
    price: "कीमत",
    truckType: "ट्रक किस्म",
    wallet: "बटुआ",
    notifications: "सूचनाएं",
    dieselCalculator: "डीजल कैलकुलेटर",
    fastag: "फास्टैग",
    hiring: "भर्ती",
    subscriptions: "सदस्यता",
    admin: "एडमिन",
    logout: "लॉगआउट",
    login: "लॉगिन",
    register: "रजिस्टर",
    profile: "प्रोफाइल",
    settings: "सेटिंग",
    save: "सेव करो",
    cancel: "रद्द करो",
    submit: "जमा करो",
    close: "बंद करो",
    edit: "संपादन",
    delete: "हटाओ",
    approve: "मंजूर",
    block: "ब्लॉक",
    apply: "आवेदन",
    calculate: "गणना",
    recharge: "रिचार्ज",
    withdraw: "निकालो",
    addMoney: "पैसे जोड़ो",
    markAllRead: "सब पढ़ा",
    pending: "लंबित",
    accepted: "स्वीकृत",
    loading: "लोड हो रिया",
    inTransit: "रस्ते पर",
    delivered: "डिलीवर",
    cancelled: "रद्द",
    driver: "ड्राइवर",
    truckOwner: "ट्रक मालिक",
    transporter: "ट्रांसपोर्टर",
    helper: "मददगार",
    gpsTracking: "GPS ट्रैकिंग",
    returnLoad: "वापसी माल",
    paymentSystem: "भुगतान प्रणाली",
    tripManagement: "यात्रा प्रबंधन",
    jobs: "नौकरियां",
    postJob: "नौकरी पोस्ट",
  },
  MNI: {
    home: "হোম",
    loads: "লোড",
    trips: "থম্বল",
    drivers: "ড্রাইভার",
    more: "অতোপ্পা",
    dashboard: "ড্যাশবোর্ড",
    myTrucks: "ঐগী ট্রাক",
    activeTrips: "একটিভ থম্বল",
    totalDrivers: "অমুক ড্রাইভার",
    monthlyEarnings: "নত্রগা লোন্থোকপা",
    addTruck: "ট্রাক থমজিনু",
    postLoad: "লোড পোস্ট",
    addDriver: "ড্রাইভার থমজিনু",
    hireHelper: "হেল্পর রাখু",
    availableLoads: "পাওখিবা লোড",
    earnings: "লোন্থোকপা",
    postedLoads: "পোস্ট লোড",
    findLoads: "লোড হন্না",
    filterLoads: "লোড ফিলটর",
    searchLoads: "লোড সর্চ",
    pickup: "পিকআপ",
    delivery: "ডেলিভারি",
    distance: "অংদি",
    weight: "ওজন",
    price: "মরি",
    truckType: "ট্রাক খুদোং",
    wallet: "ওয়ালেট",
    notifications: "নোটিফিকেশন",
    dieselCalculator: "ডিজেল ক্যালকুলেটর",
    fastag: "ফাস্টাগ",
    hiring: "হায়রিং",
    subscriptions: "সাবস্ক্রিপশন",
    admin: "এডমিন",
    logout: "লগআউট",
    login: "লগিন",
    register: "রেজিস্টার",
    profile: "প্রোফাইল",
    settings: "সেটিং",
    save: "সেভ",
    cancel: "ক্যানসেল",
    submit: "সাবমিট",
    close: "ক্লোজ",
    edit: "এডিট",
    delete: "ডিলিট",
    approve: "এপ্রুভ",
    block: "ব্লক",
    apply: "আপ্লাই",
    calculate: "ক্যালকুলেট",
    recharge: "রিচার্জ",
    withdraw: "উইদড্র",
    addMoney: "পয়সা থমজিনু",
    markAllRead: "অমুক পানবা",
    pending: "পেন্ডিং",
    accepted: "একসেপ্টেড",
    loading: "লোডিং",
    inTransit: "ট্রানজিটতা",
    delivered: "ডেলিভার্ড",
    cancelled: "ক্যানসেলড",
    driver: "ড্রাইভার",
    truckOwner: "ট্রাক মালিক",
    transporter: "ট্রান্সপোর্টার",
    helper: "হেল্পর",
    gpsTracking: "GPS ট্রাকিং",
    returnLoad: "রিটার্ন লোড",
    paymentSystem: "পেমেন্ট সিস্টেম",
    tripManagement: "থম্বল ম্যানেজমেন্ট",
    jobs: "জব",
    postJob: "জব পোস্ট",
  },
  BRX: {
    home: "होम",
    loads: "माल",
    trips: "दावस",
    drivers: "ड्राइवर",
    more: "आरो",
    dashboard: "डैशबोर्ड",
    myTrucks: "मोन ट्रक",
    activeTrips: "सक्रिय दावस",
    totalDrivers: "जेब ड्राइवर",
    monthlyEarnings: "बिसोर कमाई",
    addTruck: "ट्रक गाव",
    postLoad: "माल पोस्ट",
    addDriver: "ड्राइवर गाव",
    hireHelper: "हेल्पर राख",
    availableLoads: "उपलब्ध माल",
    earnings: "कमाई",
    postedLoads: "पोस्ट माल",
    findLoads: "माल बिथाउ",
    filterLoads: "माल फिल्टर",
    searchLoads: "माल बिथाय",
    pickup: "पिकअप",
    delivery: "डिलीवरी",
    distance: "दूरि",
    weight: "बोरथिनि",
    price: "दाम",
    truckType: "ट्रक रांगा",
    wallet: "वालेट",
    notifications: "सूचना",
    dieselCalculator: "डीजल कैलकुलेटर",
    fastag: "फास्टैग",
    hiring: "भर्ती",
    subscriptions: "सदस्यता",
    admin: "एडमिन",
    logout: "लॉगआउट",
    login: "लॉगिन",
    register: "रजिस्टर",
    profile: "प्रोफाइल",
    settings: "सेटिंग",
    save: "सेव",
    cancel: "रद्द",
    submit: "जमा",
    close: "बंद",
    edit: "संपादन",
    delete: "हटाय",
    approve: "मंजूर",
    block: "ब्लॉक",
    apply: "आवेदन",
    calculate: "गणना",
    recharge: "रिचार्ज",
    withdraw: "निकालाय",
    addMoney: "पैसा गाव",
    markAllRead: "सब पड़ा",
    pending: "लंबित",
    accepted: "स्वीकृत",
    loading: "लोड होनाय",
    inTransit: "रास्तायाव",
    delivered: "डिलीवर",
    cancelled: "रद्द",
    driver: "ड्राइवर",
    truckOwner: "ट्रक मालिक",
    transporter: "ट्रांसपोर्टर",
    helper: "हेल्पर",
    gpsTracking: "GPS ट्रैकिंग",
    returnLoad: "फिरगिर माल",
    paymentSystem: "भुगतान थाखो",
    tripManagement: "दावस थाखो",
    jobs: "नौकरि",
    postJob: "नौकरि पोस्ट",
  },
  SAT: {
    home: "ᱦᱩᱢ",
    loads: "ᱢᱟᱞ",
    trips: "ᱥᱤᱧ",
    drivers: "ᱫᱽᱨᱟᱭᱵᱷᱟᱨ",
    more: "ᱤᱧ",
    dashboard: "ᱰᱮᱥᱵᱚᱨᱰ",
    myTrucks: "ᱟᱢᱟᱜ ᱴᱨᱟᱠ",
    activeTrips: "ᱮᱠᱴᱤᱵᱷ ᱥᱤᱧ",
    totalDrivers: "ᱡᱩᱰᱤᱫ ᱫᱽᱨᱟᱭᱵᱷᱟᱨ",
    monthlyEarnings: "ᱢᱟᱦᱟ ᱠᱚᱢᱟᱤ",
    addTruck: "ᱴᱨᱟᱠ ᱡᱚᱲᱟᱣ",
    postLoad: "ᱢᱟᱞ ᱯᱚᱥᱴ",
    addDriver: "ᱫᱽᱨᱟᱭᱵᱷᱟᱨ ᱡᱚᱲᱟᱣ",
    hireHelper: "ᱦᱮᱞᱯᱟᱨ ᱨᱟᱠᱦᱩ",
    availableLoads: "ᱠᱟᱹᱢᱤ ᱢᱟᱞ",
    earnings: "ᱠᱚᱢᱟᱤ",
    postedLoads: "ᱯᱚᱥᱴ ᱢᱟᱞ",
    findLoads: "ᱢᱟᱞ ᱦᱩᱰᱤᱧ",
    filterLoads: "ᱢᱟᱞ ᱯᱷᱤᱞᱴᱟᱨ",
    searchLoads: "ᱢᱟᱞ ᱦᱩᱰᱤᱧ",
    pickup: "ᱯᱤᱠᱟᱯ",
    delivery: "ᱰᱮᱞᱤᱵᱷᱨᱤ",
    distance: "ᱫᱩᱨᱤ",
    weight: "ᱵᱷᱟᱨ",
    price: "ᱫᱟᱢ",
    truckType: "ᱴᱨᱟᱠ ᱨᱮᱱ",
    wallet: "ᱣᱟᱞᱮᱴ",
    notifications: "ᱱᱚᱴᱤᱯᱷᱤᱠᱮᱥᱚᱱ",
    dieselCalculator: "ᱰᱤᱡᱮᱞ ᱠᱮᱞᱠᱩᱞᱮᱴᱟᱨ",
    fastag: "ᱯᱷᱟᱥᱴᱮᱜ",
    hiring: "ᱵᱷᱨᱟᱛᱤ",
    subscriptions: "ᱥᱟᱵᱥᱠᱨᱤᱯᱥᱚᱱ",
    admin: "ᱮᱰᱢᱤᱱ",
    logout: "ᱞᱚᱜᱟᱣᱴ",
    login: "ᱞᱚᱜᱤᱱ",
    register: "ᱨᱮᱡᱤᱥᱴᱟᱨ",
    profile: "ᱯᱨᱚᱯᱷᱟᱭᱞ",
    settings: "ᱥᱮᱴᱤᱧ",
    save: "ᱥᱮᱵᱷ",
    cancel: "ᱨᱟᱫ",
    submit: "ᱡᱚᱢᱟ",
    close: "ᱵᱚᱱᱫ",
    edit: "ᱮᱰᱤᱴ",
    delete: "ᱦᱚᱴᱟᱣ",
    approve: "ᱢᱚᱱᱡᱩᱨ",
    block: "ᱵᱞᱚᱠ",
    apply: "ᱟᱵᱮᱫᱚᱱ",
    calculate: "ᱜᱚᱱᱚᱱᱟ",
    recharge: "ᱨᱤᱪᱟᱨᱡ",
    withdraw: "ᱱᱤᱠᱟᱞᱩ",
    addMoney: "ᱯᱮᱥᱟ ᱡᱚᱲᱟᱣ",
    markAllRead: "ᱥᱚᱵ ᱯᱚᱲᱦᱩ",
    pending: "ᱞᱚᱢᱵᱤᱛ",
    accepted: "ᱥᱣᱤᱠᱩᱨᱛ",
    loading: "ᱞᱚᱰ ᱦᱚᱱᱟ",
    inTransit: "ᱨᱟᱥᱛᱟᱛᱮ",
    delivered: "ᱰᱮᱞᱤᱵᱷᱨ",
    cancelled: "ᱨᱟᱫ",
    driver: "ᱫᱽᱨᱟᱭᱵᱷᱟᱨ",
    truckOwner: "ᱴᱨᱟᱠ ᱢᱟᱞᱤᱠ",
    transporter: "ᱴᱨᱟᱱᱥᱯᱚᱨᱴᱟᱨ",
    helper: "ᱦᱮᱞᱯᱟᱨ",
    gpsTracking: "GPS ᱴᱨᱮᱠᱤᱧ",
    returnLoad: "ᱵᱟᱯᱥᱤ ᱢᱟᱞ",
    paymentSystem: "ᱯᱮᱢᱮᱱᱴ ᱥᱤᱥᱴᱮᱢ",
    tripManagement: "ᱥᱤᱧ ᱢᱮᱱᱮᱡᱢᱮᱱᱴ",
    jobs: "ᱱᱚᱣᱠᱨᱤ",
    postJob: "ᱱᱚᱣᱠᱨᱤ ᱯᱚᱥᱴ",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "EN",
  setLanguage: () => {},
  t: translations.EN,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("EN");

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, t: translations[language] }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
