/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const NotificationType = IDL.Variant({
  'loadAlert' : IDL.Null,
  'tripUpdate' : IDL.Null,
  'paymentUpdate' : IDL.Null,
  'jobAlert' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'credit' : IDL.Null,
  'debit' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const JobRoleType = IDL.Variant({
  'helper' : IDL.Null,
  'driver' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'transporter' : IDL.Null,
  'jobSeeker' : IDL.Null,
  'truckOwner' : IDL.Null,
  'driver' : IDL.Null,
});
export const SubscriptionPlan = IDL.Variant({
  'premium' : IDL.Null,
  'basic' : IDL.Null,
  'standard' : IDL.Null,
});
export const JobPosting = IDL.Record({
  'status' : IDL.Bool,
  'roleType' : JobRoleType,
  'postedBy' : IDL.Principal,
  'salary' : IDL.Nat,
  'experienceRequired' : IDL.Nat,
  'truckType' : IDL.Text,
  'location' : IDL.Text,
  'applicants' : IDL.Vec(IDL.Principal),
});
export const LoadStatus = IDL.Variant({
  'open' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
  'negotiating' : IDL.Null,
});
export const LoadListing = IDL.Record({
  'status' : LoadStatus,
  'postedBy' : IDL.Principal,
  'weightTons' : IDL.Nat,
  'distanceKm' : IDL.Nat,
  'deliveryLocation' : IDL.Text,
  'basePriceRs' : IDL.Nat,
  'truckTypeRequired' : IDL.Text,
  'pickupLocation' : IDL.Text,
});
export const TripStatus = IDL.Variant({
  'loading' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'inTransit' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Trip = IDL.Record({
  'status' : TripStatus,
  'truckId' : IDL.Text,
  'driverId' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'createdAt' : IDL.Int,
  'loadId' : IDL.Text,
  'distanceKm' : IDL.Nat,
  'deliveryLocation' : IDL.Text,
  'remainingAmountRs' : IDL.Nat,
  'advanceAmountRs' : IDL.Nat,
  'pickupLocation' : IDL.Text,
  'agreedPriceRs' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'blocked' : IDL.Null,
  'approved' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userRole' : UserRole,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'subscriptionPlan' : SubscriptionPlan,
  'approvalStatus' : ApprovalStatus,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const Driver = IDL.Record({
  'assignedTruckId' : IDL.Opt(IDL.Principal),
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'emergencyContact' : IDL.Text,
  'experienceYears' : IDL.Nat,
  'licenseNumber' : IDL.Text,
  'aadhaarVerified' : IDL.Bool,
  'currentLocation' : IDL.Text,
  'phone' : IDL.Text,
  'licenseExpiry' : IDL.Int,
  'availabilityStatus' : IDL.Bool,
});
export const Helper = IDL.Record({
  'assignedTruckId' : IDL.Opt(IDL.Text),
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'experienceYears' : IDL.Nat,
  'aadhaarVerified' : IDL.Bool,
  'phone' : IDL.Text,
  'skills' : IDL.Text,
  'availabilityStatus' : IDL.Bool,
});
export const Notification = IDL.Record({
  'notificationType' : NotificationType,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Truck = IDL.Record({
  'ownerId' : IDL.Principal,
  'fastagNumber' : IDL.Text,
  'insuranceDetails' : IDL.Text,
  'assignedDriverId' : IDL.Opt(IDL.Principal),
  'truckType' : IDL.Text,
  'loadCapacity' : IDL.Nat,
  'permitDetails' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'truckNumber' : IDL.Text,
});
export const Transaction = IDL.Record({
  'transactionType' : TransactionType,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});
export const Wallet = IDL.Record({
  'balance' : IDL.Nat,
  'transactions' : IDL.Vec(Transaction),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDriver' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
        IDL.Int,
        IDL.Nat,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addHelper' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Text, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'addNotification' : IDL.Func([IDL.Text, NotificationType], [], []),
  'addTransaction' : IDL.Func([IDL.Nat, TransactionType, IDL.Text], [], []),
  'addTruck' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'applyForJob' : IDL.Func([IDL.Text], [], []),
  'approveUser' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'closeJobPosting' : IDL.Func([IDL.Text], [], []),
  'createJobPosting' : IDL.Func(
      [IDL.Text, JobRoleType, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'createLoadListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'createTrip' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'createUserProfile' : IDL.Func(
      [UserRole, IDL.Text, IDL.Text, IDL.Text, SubscriptionPlan],
      [],
      [],
    ),
  'createWallet' : IDL.Func([], [], []),
  'getAdminStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'activeTrips' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'pendingVerifications' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getAllLoads' : IDL.Func([], [IDL.Vec(LoadListing)], ['query']),
  'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getDriver' : IDL.Func([IDL.Principal], [Driver], ['query']),
  'getHelper' : IDL.Func([IDL.Principal], [Helper], ['query']),
  'getJobPosting' : IDL.Func([IDL.Text], [JobPosting], ['query']),
  'getLoadListing' : IDL.Func([IDL.Text], [LoadListing], ['query']),
  'getMyLoadListings' : IDL.Func([], [IDL.Vec(LoadListing)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPublicJobPostings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, JobPosting))],
      ['query'],
    ),
  'getPublicLoadListings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, LoadListing))],
      ['query'],
    ),
  'getTrip' : IDL.Func([IDL.Text], [Trip], ['query']),
  'getTruck' : IDL.Func([IDL.Text], [Truck], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTrips' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Trip))],
      ['query'],
    ),
  'getWallet' : IDL.Func([], [IDL.Opt(Wallet)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDriver' : IDL.Func(
      [
        IDL.Principal,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
        IDL.Int,
        IDL.Nat,
        IDL.Text,
        IDL.Bool,
        IDL.Opt(IDL.Principal),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateHelper' : IDL.Func(
      [
        IDL.Principal,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateLoadListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        LoadStatus,
      ],
      [],
      [],
    ),
  'updateTripStatus' : IDL.Func([IDL.Text, TripStatus], [], []),
  'updateTruck' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Principal),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const NotificationType = IDL.Variant({
    'loadAlert' : IDL.Null,
    'tripUpdate' : IDL.Null,
    'paymentUpdate' : IDL.Null,
    'jobAlert' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'credit' : IDL.Null,
    'debit' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const JobRoleType = IDL.Variant({ 'helper' : IDL.Null, 'driver' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'transporter' : IDL.Null,
    'jobSeeker' : IDL.Null,
    'truckOwner' : IDL.Null,
    'driver' : IDL.Null,
  });
  const SubscriptionPlan = IDL.Variant({
    'premium' : IDL.Null,
    'basic' : IDL.Null,
    'standard' : IDL.Null,
  });
  const JobPosting = IDL.Record({
    'status' : IDL.Bool,
    'roleType' : JobRoleType,
    'postedBy' : IDL.Principal,
    'salary' : IDL.Nat,
    'experienceRequired' : IDL.Nat,
    'truckType' : IDL.Text,
    'location' : IDL.Text,
    'applicants' : IDL.Vec(IDL.Principal),
  });
  const LoadStatus = IDL.Variant({
    'open' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
    'negotiating' : IDL.Null,
  });
  const LoadListing = IDL.Record({
    'status' : LoadStatus,
    'postedBy' : IDL.Principal,
    'weightTons' : IDL.Nat,
    'distanceKm' : IDL.Nat,
    'deliveryLocation' : IDL.Text,
    'basePriceRs' : IDL.Nat,
    'truckTypeRequired' : IDL.Text,
    'pickupLocation' : IDL.Text,
  });
  const TripStatus = IDL.Variant({
    'loading' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'inTransit' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Trip = IDL.Record({
    'status' : TripStatus,
    'truckId' : IDL.Text,
    'driverId' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'createdAt' : IDL.Int,
    'loadId' : IDL.Text,
    'distanceKm' : IDL.Nat,
    'deliveryLocation' : IDL.Text,
    'remainingAmountRs' : IDL.Nat,
    'advanceAmountRs' : IDL.Nat,
    'pickupLocation' : IDL.Text,
    'agreedPriceRs' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'blocked' : IDL.Null,
    'approved' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'userRole' : UserRole,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'subscriptionPlan' : SubscriptionPlan,
    'approvalStatus' : ApprovalStatus,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const Driver = IDL.Record({
    'assignedTruckId' : IDL.Opt(IDL.Principal),
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'emergencyContact' : IDL.Text,
    'experienceYears' : IDL.Nat,
    'licenseNumber' : IDL.Text,
    'aadhaarVerified' : IDL.Bool,
    'currentLocation' : IDL.Text,
    'phone' : IDL.Text,
    'licenseExpiry' : IDL.Int,
    'availabilityStatus' : IDL.Bool,
  });
  const Helper = IDL.Record({
    'assignedTruckId' : IDL.Opt(IDL.Text),
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'experienceYears' : IDL.Nat,
    'aadhaarVerified' : IDL.Bool,
    'phone' : IDL.Text,
    'skills' : IDL.Text,
    'availabilityStatus' : IDL.Bool,
  });
  const Notification = IDL.Record({
    'notificationType' : NotificationType,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Truck = IDL.Record({
    'ownerId' : IDL.Principal,
    'fastagNumber' : IDL.Text,
    'insuranceDetails' : IDL.Text,
    'assignedDriverId' : IDL.Opt(IDL.Principal),
    'truckType' : IDL.Text,
    'loadCapacity' : IDL.Nat,
    'permitDetails' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'truckNumber' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'transactionType' : TransactionType,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const Wallet = IDL.Record({
    'balance' : IDL.Nat,
    'transactions' : IDL.Vec(Transaction),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDriver' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          IDL.Int,
          IDL.Nat,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addHelper' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Text, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'addNotification' : IDL.Func([IDL.Text, NotificationType], [], []),
    'addTransaction' : IDL.Func([IDL.Nat, TransactionType, IDL.Text], [], []),
    'addTruck' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'applyForJob' : IDL.Func([IDL.Text], [], []),
    'approveUser' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'closeJobPosting' : IDL.Func([IDL.Text], [], []),
    'createJobPosting' : IDL.Func(
        [IDL.Text, JobRoleType, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'createLoadListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'createTrip' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'createUserProfile' : IDL.Func(
        [UserRole, IDL.Text, IDL.Text, IDL.Text, SubscriptionPlan],
        [],
        [],
      ),
    'createWallet' : IDL.Func([], [], []),
    'getAdminStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'activeTrips' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'pendingVerifications' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getAllLoads' : IDL.Func([], [IDL.Vec(LoadListing)], ['query']),
    'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getDriver' : IDL.Func([IDL.Principal], [Driver], ['query']),
    'getHelper' : IDL.Func([IDL.Principal], [Helper], ['query']),
    'getJobPosting' : IDL.Func([IDL.Text], [JobPosting], ['query']),
    'getLoadListing' : IDL.Func([IDL.Text], [LoadListing], ['query']),
    'getMyLoadListings' : IDL.Func([], [IDL.Vec(LoadListing)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPublicJobPostings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, JobPosting))],
        ['query'],
      ),
    'getPublicLoadListings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, LoadListing))],
        ['query'],
      ),
    'getTrip' : IDL.Func([IDL.Text], [Trip], ['query']),
    'getTruck' : IDL.Func([IDL.Text], [Truck], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTrips' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Trip))],
        ['query'],
      ),
    'getWallet' : IDL.Func([], [IDL.Opt(Wallet)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDriver' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          IDL.Int,
          IDL.Nat,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(IDL.Principal),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateHelper' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateLoadListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          LoadStatus,
        ],
        [],
        [],
      ),
    'updateTripStatus' : IDL.Func([IDL.Text, TripStatus], [], []),
    'updateTruck' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Principal),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };