/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'blocked' : null } |
  { 'approved' : null };
export interface Driver {
  'assignedTruckId' : [] | [Principal],
  'ownerId' : Principal,
  'name' : string,
  'emergencyContact' : string,
  'experienceYears' : bigint,
  'licenseNumber' : string,
  'aadhaarVerified' : boolean,
  'currentLocation' : string,
  'phone' : string,
  'licenseExpiry' : bigint,
  'availabilityStatus' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface Helper {
  'assignedTruckId' : [] | [string],
  'ownerId' : Principal,
  'name' : string,
  'experienceYears' : bigint,
  'aadhaarVerified' : boolean,
  'phone' : string,
  'skills' : string,
  'availabilityStatus' : boolean,
}
export interface JobPosting {
  'status' : boolean,
  'roleType' : JobRoleType,
  'postedBy' : Principal,
  'salary' : bigint,
  'experienceRequired' : bigint,
  'truckType' : string,
  'location' : string,
  'applicants' : Array<Principal>,
}
export type JobRoleType = { 'helper' : null } |
  { 'driver' : null };
export interface LoadListing {
  'status' : LoadStatus,
  'postedBy' : Principal,
  'weightTons' : bigint,
  'distanceKm' : bigint,
  'deliveryLocation' : string,
  'basePriceRs' : bigint,
  'truckTypeRequired' : string,
  'pickupLocation' : string,
}
export type LoadStatus = { 'open' : null } |
  { 'completed' : null } |
  { 'confirmed' : null } |
  { 'negotiating' : null };
export interface Notification {
  'notificationType' : NotificationType,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : bigint,
}
export type NotificationType = { 'loadAlert' : null } |
  { 'tripUpdate' : null } |
  { 'paymentUpdate' : null } |
  { 'jobAlert' : null };
export type SubscriptionPlan = { 'premium' : null } |
  { 'basic' : null } |
  { 'standard' : null };
export interface Transaction {
  'transactionType' : TransactionType,
  'description' : string,
  'timestamp' : bigint,
  'amount' : bigint,
}
export type TransactionType = { 'credit' : null } |
  { 'debit' : null };
export interface Trip {
  'status' : TripStatus,
  'truckId' : string,
  'driverId' : string,
  'paymentStatus' : string,
  'createdAt' : bigint,
  'loadId' : string,
  'distanceKm' : bigint,
  'deliveryLocation' : string,
  'remainingAmountRs' : bigint,
  'advanceAmountRs' : bigint,
  'pickupLocation' : string,
  'agreedPriceRs' : bigint,
}
export type TripStatus = { 'loading' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'inTransit' : null } |
  { 'delivered' : null } |
  { 'accepted' : null };
export interface Truck {
  'ownerId' : Principal,
  'fastagNumber' : string,
  'insuranceDetails' : string,
  'assignedDriverId' : [] | [Principal],
  'truckType' : string,
  'loadCapacity' : bigint,
  'permitDetails' : string,
  'photo' : [] | [ExternalBlob],
  'truckNumber' : string,
}
export interface UserProfile {
  'userRole' : UserRole,
  'principal' : Principal,
  'name' : string,
  'subscriptionPlan' : SubscriptionPlan,
  'approvalStatus' : ApprovalStatus,
  'phone' : string,
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'transporter' : null } |
  { 'jobSeeker' : null } |
  { 'truckOwner' : null } |
  { 'driver' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Wallet {
  'balance' : bigint,
  'transactions' : Array<Transaction>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDriver' : ActorMethod<
    [string, string, boolean, string, bigint, bigint, string, boolean, string],
    undefined
  >,
  'addHelper' : ActorMethod<
    [string, string, boolean, string, bigint, boolean],
    undefined
  >,
  'addNotification' : ActorMethod<[string, NotificationType], undefined>,
  'addTransaction' : ActorMethod<[bigint, TransactionType, string], undefined>,
  'addTruck' : ActorMethod<
    [string, string, bigint, string, string, string, [] | [ExternalBlob]],
    undefined
  >,
  'applyForJob' : ActorMethod<[string], undefined>,
  'approveUser' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'closeJobPosting' : ActorMethod<[string], undefined>,
  'createJobPosting' : ActorMethod<
    [string, JobRoleType, bigint, string, bigint, string],
    undefined
  >,
  'createLoadListing' : ActorMethod<
    [string, string, string, bigint, bigint, string, bigint],
    undefined
  >,
  'createTrip' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      string,
      string,
      string,
      bigint,
    ],
    undefined
  >,
  'createUserProfile' : ActorMethod<
    [UserRole, string, string, string, SubscriptionPlan],
    undefined
  >,
  'createWallet' : ActorMethod<[], undefined>,
  'getAdminStats' : ActorMethod<
    [],
    {
      'activeTrips' : bigint,
      'totalUsers' : bigint,
      'pendingVerifications' : bigint,
    }
  >,
  'getAllJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getAllLoads' : ActorMethod<[], Array<LoadListing>>,
  'getAllTrips' : ActorMethod<[], Array<Trip>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getDriver' : ActorMethod<[Principal], Driver>,
  'getHelper' : ActorMethod<[Principal], Helper>,
  'getJobPosting' : ActorMethod<[string], JobPosting>,
  'getLoadListing' : ActorMethod<[string], LoadListing>,
  'getMyLoadListings' : ActorMethod<[], Array<LoadListing>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPublicJobPostings' : ActorMethod<[], Array<[string, JobPosting]>>,
  'getPublicLoadListings' : ActorMethod<[], Array<[string, LoadListing]>>,
  'getTrip' : ActorMethod<[string], Trip>,
  'getTruck' : ActorMethod<[string], Truck>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTrips' : ActorMethod<[], Array<[string, Trip]>>,
  'getWallet' : ActorMethod<[], [] | [Wallet]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDriver' : ActorMethod<
    [
      Principal,
      string,
      string,
      boolean,
      string,
      bigint,
      bigint,
      string,
      boolean,
      [] | [Principal],
      string,
    ],
    undefined
  >,
  'updateHelper' : ActorMethod<
    [
      Principal,
      string,
      string,
      boolean,
      string,
      bigint,
      [] | [string],
      boolean,
    ],
    undefined
  >,
  'updateLoadListing' : ActorMethod<
    [string, string, string, bigint, bigint, string, bigint, LoadStatus],
    undefined
  >,
  'updateTripStatus' : ActorMethod<[string, TripStatus], undefined>,
  'updateTruck' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      string,
      string,
      [] | [ExternalBlob],
      [] | [Principal],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];