/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Trip {
    status: TripStatus;
    truckId: string;
    driverId: string;
    paymentStatus: string;
    createdAt: bigint;
    loadId: string;
    distanceKm: bigint;
    deliveryLocation: string;
    remainingAmountRs: bigint;
    advanceAmountRs: bigint;
    pickupLocation: string;
    agreedPriceRs: bigint;
}
export interface Driver {
    assignedTruckId?: Principal;
    ownerId: Principal;
    name: string;
    emergencyContact: string;
    experienceYears: bigint;
    licenseNumber: string;
    aadhaarVerified: boolean;
    currentLocation: string;
    phone: string;
    licenseExpiry: bigint;
    availabilityStatus: boolean;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface JobPosting {
    status: boolean;
    roleType: JobRoleType;
    postedBy: Principal;
    salary: bigint;
    experienceRequired: bigint;
    truckType: string;
    location: string;
    applicants: Array<Principal>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Transaction {
    transactionType: TransactionType;
    description: string;
    timestamp: bigint;
    amount: bigint;
}
export interface LoadListing {
    status: LoadStatus;
    postedBy: Principal;
    weightTons: bigint;
    distanceKm: bigint;
    deliveryLocation: string;
    basePriceRs: bigint;
    truckTypeRequired: string;
    pickupLocation: string;
}
export interface Wallet {
    balance: bigint;
    transactions: Array<Transaction>;
}
export interface Truck {
    ownerId: Principal;
    fastagNumber: string;
    insuranceDetails: string;
    assignedDriverId?: Principal;
    truckType: string;
    loadCapacity: bigint;
    permitDetails: string;
    photo?: ExternalBlob;
    truckNumber: string;
}
export interface Notification {
    notificationType: NotificationType;
    isRead: boolean;
    message: string;
    timestamp: bigint;
}
export interface Helper {
    assignedTruckId?: string;
    ownerId: Principal;
    name: string;
    experienceYears: bigint;
    aadhaarVerified: boolean;
    phone: string;
    skills: string;
    availabilityStatus: boolean;
}
export interface UserProfile {
    userRole: UserRole;
    principal: Principal;
    name: string;
    subscriptionPlan: SubscriptionPlan;
    approvalStatus: ApprovalStatus;
    phone: string;
    location: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ApprovalStatus {
    pending = "pending",
    blocked = "blocked",
    approved = "approved"
}
export enum JobRoleType {
    helper = "helper",
    driver = "driver"
}
export enum LoadStatus {
    open = "open",
    completed = "completed",
    confirmed = "confirmed",
    negotiating = "negotiating"
}
export enum NotificationType {
    loadAlert = "loadAlert",
    tripUpdate = "tripUpdate",
    paymentUpdate = "paymentUpdate",
    jobAlert = "jobAlert"
}
export enum SubscriptionPlan {
    premium = "premium",
    basic = "basic",
    standard = "standard"
}
export enum TransactionType {
    credit = "credit",
    debit = "debit"
}
export enum TripStatus {
    loading = "loading",
    cancelled = "cancelled",
    pending = "pending",
    inTransit = "inTransit",
    delivered = "delivered",
    accepted = "accepted"
}
export enum UserRole {
    admin = "admin",
    transporter = "transporter",
    jobSeeker = "jobSeeker",
    truckOwner = "truckOwner",
    driver = "driver"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDriver(name: string, phone: string, aadhaarVerified: boolean, licenseNumber: string, licenseExpiry: bigint, experienceYears: bigint, currentLocation: string, availabilityStatus: boolean, emergencyContact: string): Promise<void>;
    addHelper(name: string, phone: string, aadhaarVerified: boolean, skills: string, experienceYears: bigint, availabilityStatus: boolean): Promise<void>;
    addNotification(message: string, notificationType: NotificationType): Promise<void>;
    addTransaction(amount: bigint, transactionType: TransactionType, description: string): Promise<void>;
    addTruck(truckNumber: string, truckType: string, loadCapacity: bigint, insuranceDetails: string, permitDetails: string, fastagNumber: string, photo: ExternalBlob | null): Promise<void>;
    applyForJob(id: string): Promise<void>;
    approveUser(user: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    blockUser(user: Principal): Promise<void>;
    closeJobPosting(id: string): Promise<void>;
    createJobPosting(id: string, roleType: JobRoleType, salary: bigint, location: string, experienceRequired: bigint, truckType: string): Promise<void>;
    createLoadListing(id: string, pickupLocation: string, deliveryLocation: string, distanceKm: bigint, weightTons: bigint, truckTypeRequired: string, basePriceRs: bigint): Promise<void>;
    createTrip(id: string, loadId: string, truckId: string, driverId: string, agreedPriceRs: bigint, advanceAmountRs: bigint, remainingAmountRs: bigint, paymentStatus: string, pickupLocation: string, deliveryLocation: string, distanceKm: bigint): Promise<void>;
    createUserProfile(userRole: UserRole, name: string, phone: string, location: string, subscriptionPlan: SubscriptionPlan): Promise<void>;
    createWallet(): Promise<void>;
    getAdminStats(): Promise<{
        activeTrips: bigint;
        totalUsers: bigint;
        pendingVerifications: bigint;
    }>;
    getAllJobPostings(): Promise<Array<JobPosting>>;
    getAllLoads(): Promise<Array<LoadListing>>;
    getAllTrips(): Promise<Array<Trip>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getDriver(user: Principal): Promise<Driver>;
    getHelper(user: Principal): Promise<Helper>;
    getJobPosting(id: string): Promise<JobPosting>;
    getLoadListing(id: string): Promise<LoadListing>;
    getMyLoadListings(): Promise<Array<LoadListing>>;
    getNotifications(): Promise<Array<Notification>>;
    getPublicJobPostings(): Promise<Array<[string, JobPosting]>>;
    getPublicLoadListings(): Promise<Array<[string, LoadListing]>>;
    getTrip(id: string): Promise<Trip>;
    getTruck(truckNumber: string): Promise<Truck>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserTrips(): Promise<Array<[string, Trip]>>;
    getWallet(): Promise<Wallet | null>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationAsRead(index: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateDriver(user: Principal, name: string, phone: string, aadhaarVerified: boolean, licenseNumber: string, licenseExpiry: bigint, experienceYears: bigint, currentLocation: string, availabilityStatus: boolean, assignedTruckId: Principal | null, emergencyContact: string): Promise<void>;
    updateHelper(user: Principal, name: string, phone: string, aadhaarVerified: boolean, skills: string, experienceYears: bigint, assignedTruckId: string | null, availabilityStatus: boolean): Promise<void>;
    updateLoadListing(id: string, pickupLocation: string, deliveryLocation: string, distanceKm: bigint, weightTons: bigint, truckTypeRequired: string, basePriceRs: bigint, status: LoadStatus): Promise<void>;
    updateTripStatus(id: string, status: TripStatus): Promise<void>;
    updateTruck(truckNumber: string, truckType: string, loadCapacity: bigint, insuranceDetails: string, permitDetails: string, fastagNumber: string, photo: ExternalBlob | null, assignedDriverId: Principal | null): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, Driver as _Driver, ExternalBlob as _ExternalBlob, Helper as _Helper, JobPosting as _JobPosting, JobRoleType as _JobRoleType, LoadListing as _LoadListing, LoadStatus as _LoadStatus, Notification as _Notification, NotificationType as _NotificationType, SubscriptionPlan as _SubscriptionPlan, Transaction as _Transaction, TransactionType as _TransactionType, Trip as _Trip, TripStatus as _TripStatus, Truck as _Truck, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, Wallet as _Wallet, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDriver(arg0: string, arg1: string, arg2: boolean, arg3: string, arg4: bigint, arg5: bigint, arg6: string, arg7: boolean, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDriver(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDriver(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async addHelper(arg0: string, arg1: string, arg2: boolean, arg3: string, arg4: bigint, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHelper(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHelper(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addNotification(arg0: string, arg1: NotificationType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotification(arg0, to_candid_NotificationType_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotification(arg0, to_candid_NotificationType_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addTransaction(arg0: bigint, arg1: TransactionType, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, to_candid_TransactionType_n10(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, to_candid_TransactionType_n10(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async addTruck(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: string, arg6: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTruck(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTruck(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async applyForJob(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyForJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyForJob(arg0);
            return result;
        }
    }
    async approveUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveUser(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async closeJobPosting(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.closeJobPosting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeJobPosting(arg0);
            return result;
        }
    }
    async createJobPosting(arg0: string, arg1: JobRoleType, arg2: bigint, arg3: string, arg4: bigint, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobPosting(arg0, to_candid_JobRoleType_n16(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobPosting(arg0, to_candid_JobRoleType_n16(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createLoadListing(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: string, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createLoadListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLoadListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createTrip(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: bigint, arg7: string, arg8: string, arg9: string, arg10: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrip(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrip(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async createUserProfile(arg0: UserRole, arg1: string, arg2: string, arg3: string, arg4: SubscriptionPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, to_candid_SubscriptionPlan_n20(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, to_candid_SubscriptionPlan_n20(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async createWallet(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createWallet();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWallet();
            return result;
        }
    }
    async getAdminStats(): Promise<{
        activeTrips: bigint;
        totalUsers: bigint;
        pendingVerifications: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAllJobPostings(): Promise<Array<JobPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobPostings();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobPostings();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLoads(): Promise<Array<LoadListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLoads();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLoads();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTrips(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrips();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrips();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriver(arg0: Principal): Promise<Driver> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriver(arg0);
                return from_candid_Driver_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriver(arg0);
            return from_candid_Driver_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHelper(arg0: Principal): Promise<Helper> {
        if (this.processError) {
            try {
                const result = await this.actor.getHelper(arg0);
                return from_candid_Helper_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHelper(arg0);
            return from_candid_Helper_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobPosting(arg0: string): Promise<JobPosting> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobPosting(arg0);
                return from_candid_JobPosting_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobPosting(arg0);
            return from_candid_JobPosting_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoadListing(arg0: string): Promise<LoadListing> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoadListing(arg0);
                return from_candid_LoadListing_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoadListing(arg0);
            return from_candid_LoadListing_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyLoadListings(): Promise<Array<LoadListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLoadListings();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLoadListings();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicJobPostings(): Promise<Array<[string, JobPosting]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicJobPostings();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicJobPostings();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicLoadListings(): Promise<Array<[string, LoadListing]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicLoadListings();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicLoadListings();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrip(arg0: string): Promise<Trip> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrip(arg0);
                return from_candid_Trip_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrip(arg0);
            return from_candid_Trip_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTruck(arg0: string): Promise<Truck> {
        if (this.processError) {
            try {
                const result = await this.actor.getTruck(arg0);
                return from_candid_Truck_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTruck(arg0);
            return from_candid_Truck_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTrips(): Promise<Array<[string, Trip]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTrips();
                return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTrips();
            return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWallet(): Promise<Wallet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWallet();
                return from_candid_opt_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWallet();
            return from_candid_opt_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n78(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n78(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDriver(arg0: Principal, arg1: string, arg2: string, arg3: boolean, arg4: string, arg5: bigint, arg6: bigint, arg7: string, arg8: boolean, arg9: Principal | null, arg10: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDriver(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n82(this._uploadFile, this._downloadFile, arg9), arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDriver(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n82(this._uploadFile, this._downloadFile, arg9), arg10);
            return result;
        }
    }
    async updateHelper(arg0: Principal, arg1: string, arg2: string, arg3: boolean, arg4: string, arg5: bigint, arg6: string | null, arg7: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHelper(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n83(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHelper(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n83(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async updateLoadListing(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: string, arg6: bigint, arg7: LoadStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLoadListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_LoadStatus_n84(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLoadListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_LoadStatus_n84(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async updateTripStatus(arg0: string, arg1: TripStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTripStatus(arg0, to_candid_TripStatus_n86(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTripStatus(arg0, to_candid_TripStatus_n86(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTruck(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: string, arg6: ExternalBlob | null, arg7: Principal | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTruck(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n82(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTruck(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n82(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Driver_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Driver): Driver {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Helper_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Helper): Helper {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_JobPosting_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobPosting): JobPosting {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_JobRoleType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobRoleType): JobRoleType {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_LoadListing_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoadListing): LoadListing {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_LoadStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoadStatus): LoadStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionPlan_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionPlan): SubscriptionPlan {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n77(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n75(_uploadFile, _downloadFile, value);
}
function from_candid_TripStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripStatus): TripStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Trip_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trip): Trip {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_Truck_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Truck): Promise<Truck> {
    return await from_candid_record_n65(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Wallet_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Wallet): Wallet {
    return from_candid_record_n72(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n67(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Wallet]): Wallet | null {
    return value.length === 0 ? null : from_candid_Wallet_n71(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: boolean;
    roleType: _JobRoleType;
    postedBy: Principal;
    salary: bigint;
    experienceRequired: bigint;
    truckType: string;
    location: string;
    applicants: Array<Principal>;
}): {
    status: boolean;
    roleType: JobRoleType;
    postedBy: Principal;
    salary: bigint;
    experienceRequired: bigint;
    truckType: string;
    location: string;
    applicants: Array<Principal>;
} {
    return {
        status: value.status,
        roleType: from_candid_JobRoleType_n25(_uploadFile, _downloadFile, value.roleType),
        postedBy: value.postedBy,
        salary: value.salary,
        experienceRequired: value.experienceRequired,
        truckType: value.truckType,
        location: value.location,
        applicants: value.applicants
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _LoadStatus;
    postedBy: Principal;
    weightTons: bigint;
    distanceKm: bigint;
    deliveryLocation: string;
    basePriceRs: bigint;
    truckTypeRequired: string;
    pickupLocation: string;
}): {
    status: LoadStatus;
    postedBy: Principal;
    weightTons: bigint;
    distanceKm: bigint;
    deliveryLocation: string;
    basePriceRs: bigint;
    truckTypeRequired: string;
    pickupLocation: string;
} {
    return {
        status: from_candid_LoadStatus_n30(_uploadFile, _downloadFile, value.status),
        postedBy: value.postedBy,
        weightTons: value.weightTons,
        distanceKm: value.distanceKm,
        deliveryLocation: value.deliveryLocation,
        basePriceRs: value.basePriceRs,
        truckTypeRequired: value.truckTypeRequired,
        pickupLocation: value.pickupLocation
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TripStatus;
    truckId: string;
    driverId: string;
    paymentStatus: string;
    createdAt: bigint;
    loadId: string;
    distanceKm: bigint;
    deliveryLocation: string;
    remainingAmountRs: bigint;
    advanceAmountRs: bigint;
    pickupLocation: string;
    agreedPriceRs: bigint;
}): {
    status: TripStatus;
    truckId: string;
    driverId: string;
    paymentStatus: string;
    createdAt: bigint;
    loadId: string;
    distanceKm: bigint;
    deliveryLocation: string;
    remainingAmountRs: bigint;
    advanceAmountRs: bigint;
    pickupLocation: string;
    agreedPriceRs: bigint;
} {
    return {
        status: from_candid_TripStatus_n35(_uploadFile, _downloadFile, value.status),
        truckId: value.truckId,
        driverId: value.driverId,
        paymentStatus: value.paymentStatus,
        createdAt: value.createdAt,
        loadId: value.loadId,
        distanceKm: value.distanceKm,
        deliveryLocation: value.deliveryLocation,
        remainingAmountRs: value.remainingAmountRs,
        advanceAmountRs: value.advanceAmountRs,
        pickupLocation: value.pickupLocation,
        agreedPriceRs: value.agreedPriceRs
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userRole: _UserRole;
    principal: Principal;
    name: string;
    subscriptionPlan: _SubscriptionPlan;
    approvalStatus: _ApprovalStatus;
    phone: string;
    location: string;
}): {
    userRole: UserRole;
    principal: Principal;
    name: string;
    subscriptionPlan: SubscriptionPlan;
    approvalStatus: ApprovalStatus;
    phone: string;
    location: string;
} {
    return {
        userRole: from_candid_UserRole_n40(_uploadFile, _downloadFile, value.userRole),
        principal: value.principal,
        name: value.name,
        subscriptionPlan: from_candid_SubscriptionPlan_n42(_uploadFile, _downloadFile, value.subscriptionPlan),
        approvalStatus: from_candid_ApprovalStatus_n44(_uploadFile, _downloadFile, value.approvalStatus),
        phone: value.phone,
        location: value.location
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignedTruckId: [] | [Principal];
    ownerId: Principal;
    name: string;
    emergencyContact: string;
    experienceYears: bigint;
    licenseNumber: string;
    aadhaarVerified: boolean;
    currentLocation: string;
    phone: string;
    licenseExpiry: bigint;
    availabilityStatus: boolean;
}): {
    assignedTruckId?: Principal;
    ownerId: Principal;
    name: string;
    emergencyContact: string;
    experienceYears: bigint;
    licenseNumber: string;
    aadhaarVerified: boolean;
    currentLocation: string;
    phone: string;
    licenseExpiry: bigint;
    availabilityStatus: boolean;
} {
    return {
        assignedTruckId: record_opt_to_undefined(from_candid_opt_n51(_uploadFile, _downloadFile, value.assignedTruckId)),
        ownerId: value.ownerId,
        name: value.name,
        emergencyContact: value.emergencyContact,
        experienceYears: value.experienceYears,
        licenseNumber: value.licenseNumber,
        aadhaarVerified: value.aadhaarVerified,
        currentLocation: value.currentLocation,
        phone: value.phone,
        licenseExpiry: value.licenseExpiry,
        availabilityStatus: value.availabilityStatus
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignedTruckId: [] | [string];
    ownerId: Principal;
    name: string;
    experienceYears: bigint;
    aadhaarVerified: boolean;
    phone: string;
    skills: string;
    availabilityStatus: boolean;
}): {
    assignedTruckId?: string;
    ownerId: Principal;
    name: string;
    experienceYears: bigint;
    aadhaarVerified: boolean;
    phone: string;
    skills: string;
    availabilityStatus: boolean;
} {
    return {
        assignedTruckId: record_opt_to_undefined(from_candid_opt_n54(_uploadFile, _downloadFile, value.assignedTruckId)),
        ownerId: value.ownerId,
        name: value.name,
        experienceYears: value.experienceYears,
        aadhaarVerified: value.aadhaarVerified,
        phone: value.phone,
        skills: value.skills,
        availabilityStatus: value.availabilityStatus
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notificationType: _NotificationType;
    isRead: boolean;
    message: string;
    timestamp: bigint;
}): {
    notificationType: NotificationType;
    isRead: boolean;
    message: string;
    timestamp: bigint;
} {
    return {
        notificationType: from_candid_NotificationType_n58(_uploadFile, _downloadFile, value.notificationType),
        isRead: value.isRead,
        message: value.message,
        timestamp: value.timestamp
    };
}
async function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ownerId: Principal;
    fastagNumber: string;
    insuranceDetails: string;
    assignedDriverId: [] | [Principal];
    truckType: string;
    loadCapacity: bigint;
    permitDetails: string;
    photo: [] | [_ExternalBlob];
    truckNumber: string;
}): Promise<{
    ownerId: Principal;
    fastagNumber: string;
    insuranceDetails: string;
    assignedDriverId?: Principal;
    truckType: string;
    loadCapacity: bigint;
    permitDetails: string;
    photo?: ExternalBlob;
    truckNumber: string;
}> {
    return {
        ownerId: value.ownerId,
        fastagNumber: value.fastagNumber,
        insuranceDetails: value.insuranceDetails,
        assignedDriverId: record_opt_to_undefined(from_candid_opt_n51(_uploadFile, _downloadFile, value.assignedDriverId)),
        truckType: value.truckType,
        loadCapacity: value.loadCapacity,
        permitDetails: value.permitDetails,
        photo: record_opt_to_undefined(await from_candid_opt_n66(_uploadFile, _downloadFile, value.photo)),
        truckNumber: value.truckNumber
    };
}
function from_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    balance: bigint;
    transactions: Array<_Transaction>;
}): {
    balance: bigint;
    transactions: Array<Transaction>;
} {
    return {
        balance: value.balance,
        transactions: from_candid_vec_n73(_uploadFile, _downloadFile, value.transactions)
    };
}
function from_candid_record_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transactionType: _TransactionType;
    description: string;
    timestamp: bigint;
    amount: bigint;
}): {
    transactionType: TransactionType;
    description: string;
    timestamp: bigint;
    amount: bigint;
} {
    return {
        transactionType: from_candid_TransactionType_n76(_uploadFile, _downloadFile, value.transactionType),
        description: value.description,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_tuple_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _JobPosting]): [string, JobPosting] {
    return [
        value[0],
        from_candid_JobPosting_n23(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _LoadListing]): [string, LoadListing] {
    return [
        value[0],
        from_candid_LoadListing_n28(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _Trip]): [string, Trip] {
    return [
        value[0],
        from_candid_Trip_n33(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    helper: null;
} | {
    driver: null;
}): JobRoleType {
    return "helper" in value ? JobRoleType.helper : "driver" in value ? JobRoleType.driver : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    open: null;
} | {
    completed: null;
} | {
    confirmed: null;
} | {
    negotiating: null;
}): LoadStatus {
    return "open" in value ? LoadStatus.open : "completed" in value ? LoadStatus.completed : "confirmed" in value ? LoadStatus.confirmed : "negotiating" in value ? LoadStatus.negotiating : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    loading: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    inTransit: null;
} | {
    delivered: null;
} | {
    accepted: null;
}): TripStatus {
    return "loading" in value ? TripStatus.loading : "cancelled" in value ? TripStatus.cancelled : "pending" in value ? TripStatus.pending : "inTransit" in value ? TripStatus.inTransit : "delivered" in value ? TripStatus.delivered : "accepted" in value ? TripStatus.accepted : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    transporter: null;
} | {
    jobSeeker: null;
} | {
    truckOwner: null;
} | {
    driver: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "transporter" in value ? UserRole.transporter : "jobSeeker" in value ? UserRole.jobSeeker : "truckOwner" in value ? UserRole.truckOwner : "driver" in value ? UserRole.driver : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    basic: null;
} | {
    standard: null;
}): SubscriptionPlan {
    return "premium" in value ? SubscriptionPlan.premium : "basic" in value ? SubscriptionPlan.basic : "standard" in value ? SubscriptionPlan.standard : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    blocked: null;
} | {
    approved: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "blocked" in value ? ApprovalStatus.blocked : "approved" in value ? ApprovalStatus.approved : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    loadAlert: null;
} | {
    tripUpdate: null;
} | {
    paymentUpdate: null;
} | {
    jobAlert: null;
}): NotificationType {
    return "loadAlert" in value ? NotificationType.loadAlert : "tripUpdate" in value ? NotificationType.tripUpdate : "paymentUpdate" in value ? NotificationType.paymentUpdate : "jobAlert" in value ? NotificationType.jobAlert : value;
}
function from_candid_variant_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    credit: null;
} | {
    debit: null;
}): TransactionType {
    return "credit" in value ? TransactionType.credit : "debit" in value ? TransactionType.debit : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobPosting>): Array<JobPosting> {
    return value.map((x)=>from_candid_JobPosting_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LoadListing>): Array<LoadListing> {
    return value.map((x)=>from_candid_LoadListing_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trip>): Array<Trip> {
    return value.map((x)=>from_candid_Trip_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n56(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _JobPosting]>): Array<[string, JobPosting]> {
    return value.map((x)=>from_candid_tuple_n61(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _LoadListing]>): Array<[string, LoadListing]> {
    return value.map((x)=>from_candid_tuple_n63(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _Trip]>): Array<[string, Trip]> {
    return value.map((x)=>from_candid_tuple_n69(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n74(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n81(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_JobRoleType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobRoleType): _JobRoleType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_LoadStatus_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoadStatus): _LoadStatus {
    return to_candid_variant_n85(_uploadFile, _downloadFile, value);
}
function to_candid_NotificationType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): _NotificationType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionPlan_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionPlan): _SubscriptionPlan {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_TripStatus_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripStatus): _TripStatus {
    return to_candid_variant_n87(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n79(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userRole: UserRole;
    principal: Principal;
    name: string;
    subscriptionPlan: SubscriptionPlan;
    approvalStatus: ApprovalStatus;
    phone: string;
    location: string;
}): {
    userRole: _UserRole;
    principal: Principal;
    name: string;
    subscriptionPlan: _SubscriptionPlan;
    approvalStatus: _ApprovalStatus;
    phone: string;
    location: string;
} {
    return {
        userRole: to_candid_UserRole_n18(_uploadFile, _downloadFile, value.userRole),
        principal: value.principal,
        name: value.name,
        subscriptionPlan: to_candid_SubscriptionPlan_n20(_uploadFile, _downloadFile, value.subscriptionPlan),
        approvalStatus: to_candid_ApprovalStatus_n80(_uploadFile, _downloadFile, value.approvalStatus),
        phone: value.phone,
        location: value.location
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    credit: null;
} | {
    debit: null;
} {
    return value == TransactionType.credit ? {
        credit: null
    } : value == TransactionType.debit ? {
        debit: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobRoleType): {
    helper: null;
} | {
    driver: null;
} {
    return value == JobRoleType.helper ? {
        helper: null
    } : value == JobRoleType.driver ? {
        driver: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    transporter: null;
} | {
    jobSeeker: null;
} | {
    truckOwner: null;
} | {
    driver: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.transporter ? {
        transporter: null
    } : value == UserRole.jobSeeker ? {
        jobSeeker: null
    } : value == UserRole.truckOwner ? {
        truckOwner: null
    } : value == UserRole.driver ? {
        driver: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionPlan): {
    premium: null;
} | {
    basic: null;
} | {
    standard: null;
} {
    return value == SubscriptionPlan.premium ? {
        premium: null
    } : value == SubscriptionPlan.basic ? {
        basic: null
    } : value == SubscriptionPlan.standard ? {
        standard: null
    } : value;
}
function to_candid_variant_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    blocked: null;
} | {
    approved: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.blocked ? {
        blocked: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value;
}
function to_candid_variant_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoadStatus): {
    open: null;
} | {
    completed: null;
} | {
    confirmed: null;
} | {
    negotiating: null;
} {
    return value == LoadStatus.open ? {
        open: null
    } : value == LoadStatus.completed ? {
        completed: null
    } : value == LoadStatus.confirmed ? {
        confirmed: null
    } : value == LoadStatus.negotiating ? {
        negotiating: null
    } : value;
}
function to_candid_variant_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripStatus): {
    loading: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    inTransit: null;
} | {
    delivered: null;
} | {
    accepted: null;
} {
    return value == TripStatus.loading ? {
        loading: null
    } : value == TripStatus.cancelled ? {
        cancelled: null
    } : value == TripStatus.pending ? {
        pending: null
    } : value == TripStatus.inTransit ? {
        inTransit: null
    } : value == TripStatus.delivered ? {
        delivered: null
    } : value == TripStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): {
    loadAlert: null;
} | {
    tripUpdate: null;
} | {
    paymentUpdate: null;
} | {
    jobAlert: null;
} {
    return value == NotificationType.loadAlert ? {
        loadAlert: null
    } : value == NotificationType.tripUpdate ? {
        tripUpdate: null
    } : value == NotificationType.paymentUpdate ? {
        paymentUpdate: null
    } : value == NotificationType.jobAlert ? {
        jobAlert: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
